### ISSUE TITLE
How can I test NDP in cooja

### ISSUE THREAD

**Issue by wspark91** [contiki-ng/contiki-ng#1009]
HI!!
I want to know how to test 6lowpan-neighbor discovery in a cooja environment.

Thank you...

**Comment by yatch** [comment]
Although I'm not sure what you want to do, you may want to check `UIP_CONF_ND6_` settings in `os/net/ipv6/uip-nd6.h` or `os/contiki-default-conf.h`. To my understanding, [RFC 6775](https://tools.ietf.org/html/rfc6775) and its accompanying spec are not supported yet.

**Comment by wspark91** [comment]
I will try the test as shown below.
<img width="131" alt="NDP" src="https://user-images.githubusercontent.com/52874779/61339478-e13e2900-a878-11e9-9043-b927f52b94c4.png">

**Comment by wspark91** [comment]
> Although I'm not sure what you want to do, you may want to check `UIP_CONF_ND6_` settings in `os/net/ipv6/uip-nd6.h` or `os/contiki-default-conf.h`. To my understanding, [RFC 6775](https://tools.ietf.org/html/rfc6775) and its accompanying spec are not supported yet.

I will try the test as shown below.
<img width="131" alt="NDP" src="https://user-images.githubusercontent.com/52874779/61339478-e13e2900-a878-11e9-9043-b927f52b94c4.png">
