### ISSUE TITLE
contiki-ng over the air download

### ISSUE THREAD

**Issue by 0608rohit** [contiki-ng/contiki-ng#1012]
I am trying to perform Over The Air Download on simplelink LAUNCHXL-CC1352R1 using contiki-ng
If it supports OAD then is it possible to do multi broadcasting OAD? 

How am I suppose to start with OAD and multi broadcasting OAD using contiki-ng ? (Documentation and Link)

**Comment by 0608rohit** [comment]
Hello,
i am expecting answer from community.

**Comment by yatch** [comment]
It's not supported yet, although there is [an on-going work on OAP/OTA](https://github.com/contiki-ng/contiki-ng/pull/623).

By the way, Gitter would be a better place to ask this kind of question.  See https://github.com/contiki-ng/contiki-ng/wiki/Where-to-report-issues,-ask-questions,-etc.%3F#gitter
