### ISSUE TITLE
cc26xx web-demo for LAUNCHXL-CC1352R1

### ISSUE THREAD

**Issue by 0608rohit** [contiki-ng/contiki-ng#1014]
Hello, 
I can't  build cc26xx web-demo code for LAUNCHXL-CC1352R1 in Contiki-ng.
 please tell me which types of changes are needed for CC1352R1 ?

**Comment by 0608rohit** [comment]
Hello
I want to build example/platform-specific/cc26xx/cc26xx-web-demo code on cc13x2 platform.
is it possible? if yes then,
What step should I have to follow to change platform-specific example?(document would be helpful for me)
I am expecting answer from you.

**Comment by g-oikonomou** [comment]
This particular example is not intended for use with the simplelink platform. It has not been tested against it at all, so even if you could make it compile I would be surprised if you didn't encounter other issues. I can immediately imagine problems with the example's BLE advertisements as well as with the way it collects various sensor readings.
