### ISSUE TITLE
How can I test NDP in cooja

### ISSUE THREAD

**Issue by wspark91** [contiki-ng/contiki-ng#1016]
Hi!!!
I'm beginner.

I want to test 6LoWPAN ND protocol in cooja.

RS -> RA / NS -> NA / DAR -> DAC message...

I tried the following test.

contiki-ng/example/rpl-udp

When I compile udp-client source
os/contiki-default-conf.h

#ifdef NETSTACK_CONF_WITH_IPV6
#undef NETSTACK_CONF_WITH_IPV6
#define NETSTACK_CONF_WITH_IPV6 1
#endif

#ifdef UIP_CONF_IPV6_RPL
#undef UIP_CONF_IPV6_RPL
#define UIP_CONF_IPV6_RPL 0
#endif

#ifdef UIP_CONF_ROUTER
#undef UIP_CONF_ROUTER
#define UIP_CONF_ROUTER 0
#endif

When I compile udp-server source
#ifdef NETSTACK_CONF_WITH_IPV6
#undef NETSTACK_CONF_WITH_IPV6
#define NETSTACK_CONF_WITH_IPV6 1
#endif

#ifdef UIP_CONF_IPV6_RPL
#undef UIP_CONF_IPV6_RPL
#define UIP_CONF_IPV6_RPL 0
#endif

#ifdef UIP_CONF_ROUTER
#undef UIP_CONF_ROUTER
#define UIP_CONF_ROUTER 1
#endif

then only RS/RA message is confirmed.
But NS/NA message does not appear.

How can I test NDP in cooja?

**Comment by yatch** [comment]
Please read `os/contiki-default-conf.h` carefully.

```
/* UIP_CONF_ND6_SEND_NS enables standard IPv6 Neighbor Discovery Protocol
   (RFC 4861). We enable it by default when IPv6 is used without RPL.
   With RPL, the neighbor cache (link-local IPv6 <-> MAC address mapping)
   is fed whenever receiving DIO. This is often sufficient
   for RPL routing, i.e. to send to the preferred parent or any child.
   Link-local unicast to other neighbors may, however, not be possible if
   we never receive any DIO from them. This may happen if the link from the
   neighbor to us is weak, if DIO transmissions are suppressed (Trickle
   timer) or if the neighbor chooses not to transmit DIOs because it is
   a leaf node or for any reason. */
#ifndef UIP_CONF_ND6_SEND_NS
#if (NETSTACK_CONF_WITH_IPV6 && !UIP_CONF_IPV6_RPL)
#define UIP_CONF_ND6_SEND_NS 1
#else /* (NETSTACK_CONF_WITH_IPV6 && !UIP_CONF_IPV6_RPL) */
#define UIP_CONF_ND6_SEND_NS 0
#endif /* (NETSTACK_CONF_WITH_IPV6 && !UIP_CONF_IPV6_RPL) */
#endif /* UIP_CONF_ND6_SEND_NS */
```
Closing this issue as duplicated with https://github.com/contiki-ng/contiki-ng/issues/1009
