### ISSUE TITLE
Probing stops after global repair.

### ISSUE THREAD

**Issue by pciolkosz** [contiki-ng/contiki-ng#1026]
The problem is this line and the next one:
https://github.com/contiki-ng/contiki-ng/blob/7b4de0585224d877de53d1402df28d4d31f3eef9/os/net/routing/rpl-lite/rpl-dag.c#L231

While other timers gets rescheduled, the probing timer is not scheduled in init_dag_from_dio function, but in process_dio_init_dag, which is not called in case of global repair. This causes the node to stop probing. This sometimes leads to a group of nodes joining the new version, but not being able to find any preferred parent in it, because of high etx to the DIO sender.

**Comment by simonduq** [comment]
ood catch! Maybe we should call `process_dio_init_dag` instead.

**Comment by g-oikonomou** [comment]
Fixed in #1077
