### ISSUE TITLE
How to connect multiple BRs to Host

### ISSUE THREAD

**Issue by mcuxmx** [contiki-ng/contiki-ng#1027]
I want to connect multiple BRS to the host. Does unslip6 support it?

Can I replace the serial in tunslip6 with tcp or udp in ipv4, how does tunslip6 distinguish SLIP data from different BRs? How do I achieve it?

Thank you

**Comment by yatch** [comment]
> I want to connect multiple BRS to the host. Does unslip6 support it?

Although I've never tried it, I think it should work.

Try running `tunslip6` per BR with a different set of `tundev` and `ipaddress`:
```
$ tunslip6 -s /dev/ttyUSB0 -t tun0 fd00:1::1/64
$ tunslip6 -s /dev/ttyUSB1 -t tun1 fd00:2::1/64
```

> Can I replace the serial in tunslip6 with tcp or udp in ipv4

I don't think so. If you want to talk with Coniki-NG devices in IPv4, you will need an IPv4/IPv6 translator. See https://github.com/contiki-ng/contiki-ng/wiki/NAT64-for-Contiki‐NG, this may be helpful.
