### ISSUE TITLE
New version string

### ISSUE THREAD

**Issue by nvt** [contiki-ng/contiki-ng#103]
At startup, the first line printed is typically the CONTIKI_VERSION_STRING value set in Makefile.include, which looks like "Contiki-3.x-3638-gc1a917a". Should we change it to "Contiki-NG-3638-g1a917a", "Contiki-NG-1.x-3638-g1a917a", or something else?

**Comment by simonduq** [comment]
done in https://github.com/contiki-ng/contiki-ng/pull/117
