### ISSUE TITLE
Timing for TSCH on CC1310 LRM 

### ISSUE THREAD

**Issue by moskito-s** [contiki-ng/contiki-ng#1030]
I am trying to implement the CC1310 LRM as done in pull request #982 .
Because of timing issues TSCH does not work. It is obvious that I need to create a new timing file for the 5kbps LRM Mode just like the " cc13xx-50kbps-tsch.c". I am however lost where to start. What would be the best approch to change the definitions:

```
1. #define CC13XX_TSCH_DEFAULT_TS_CCA_OFFSET         1800
2. #define CC13XX_TSCH_DEFAULT_TS_CCA                128
3. #define CC13XX_TSCH_DEFAULT_TS_TX_OFFSET          2500
4. #define CC13XX_TSCH_DEFAULT_TS_RX_OFFSET          (CC13XX_TSCH_DEFAULT_TS_TX_OFFSET - (TSCH_CONF_RX_WAIT / 2))
5. #define CC13XX_TSCH_DEFAULT_TS_RX_ACK_DELAY       2000
6. #define CC13XX_TSCH_DEFAULT_TS_TX_ACK_DELAY       3000
7. #define CC13XX_TSCH_DEFAULT_TS_RX_WAIT            TSCH_CONF_RX_WAIT
8. #define CC13XX_TSCH_DEFAULT_TS_ACK_WAIT           3000
9. #define CC13XX_TSCH_DEFAULT_TS_RX_TX              192
10. #define CC13XX_TSCH_DEFAULT_TS_MAX_ACK            10000
11. #define CC13XX_TSCH_DEFAULT_TS_MAX_TX             21600
```
I could not find a documentation what each definition does exactly.

**Comment by rajeev1986** [comment]
Hi @moskito-s,
As a start, it is wise to use macros to compile a different version of the TSCH network i.e, for instance, `CC1310_LRM` for compiling long-range mode that will take  TSCH timing for 5kbps: **cc13xx-5kbps-tsch.c** while `CC1310_GFSK` can be for the default 50kbps network. You may want to do this in `arch/cpu/cc26x0-cc13x0/Makefile.cc26x0-cc13x0`. This setting should also be reflected in  `arch/cpu/cc26x0-cc13x0/cc13xx-cc26xx-def.h` taking correct `TSCH_CONF_DEFAULT_TIMESLOT_TIMING` file into account. From 50kbps to 5kbps, it's a factor of 10 so keep that in mind when tuning the TSCH slot timings for 5kbps. The `CC13XX_TSCH_DEFAULT_TS_TIMESLOT_LENGTH` will also increase, respectively. Good literature for understanding the TSCH timings is [IEEE Standard for Low-Rate Wireless Networks](https://ieeexplore.ieee.org/document/7460875) pgs 95-98, 350. 

Once this is sorted out, then change your TSCH timing for the respective network. Moreover, you also need to change `RAT_TIMESTAMP_OFFSET_SUB_GHZ USEC_TO_RADIO` for correct synchronization. Tune this value to keep the `dr` in TSCH logs close to zero for least synchronization error. 5kbps mode will need experiments to tune this number. The fastest way is to take two nodes, flash each with the firmware and experiment. 

Let's see how it goes...
