### ISSUE TITLE
Zolertia REMOTE B - SD CARD PROBLEM

### ISSUE THREAD

**Issue by akaralis** [contiki-ng/contiki-ng#1032]
I tried to use an SD card in a zolertia remote (revision B), but Contiki could not find a valid FAT32 partition. 
I checked that the sd card has a valid FAT32 partition, and then i started to do a detailed analysis of the related code.
I found that sector 0 is not read correctly. Instead, only the first 6 bytes are read correctly.
The problem is located in the function mmc_arch_spi_xfer in arch/platform/zoul/dev/mmc-arch.c.
I think that the problem is caused by the statement "SPIX_BUF(USD_SPI_INSTANCE) = 0".
If I'm not mistaken, when using SPI, the value 0xFF should be sent in order to read data from the MMC.
I changed the aforementioned statement to "SPIX_BUF(USD_SPI_INSTANCE) = 0xFF" and now the sd card works perfectly.

Please check this problem.

**Comment by g-oikonomou** [comment]
Hi

Thanks for this. Can you turn what you said to a pull request please? Otherwise this could fall through the cracks. I don't have a card handy to check this.
