### ISSUE TITLE
udp_conn == NULL  problem

### ISSUE THREAD

**Issue by fanleung** [contiki-ng/contiki-ng#1034]
Hello, everyone. I had this problem when I was doing some experiments.There's a BR and a leaf node. Leaf node has been
link to BR. 
[INFO: RPL       ] nbr: end of list
[INFO: RPL       ] links: 2 routing links in total (Periodic)
[INFO: RPL       ] links: fd00::212:4b00:17ae:ee14  (DODAG root) (lifetime: infinite)
[INFO: RPL       ] links: fd00::212:4b00:1c7a:65c0  to fd00::212:4b00:17ae:ee14 (lifetime: 120 seconds)
And then the leaf node will sends UDP information to BR at regular intervals through 
```
if(NETSTACK_ROUTING.node_is_reachable() && NETSTACK_ROUTING.get_root_ipaddr(&dest_ipaddr)) {
    simple_udp_sendto(...)
}
```
I put BR power off,  until the leaf node know it was dropped and leave the network, I put BR power on again, let the leaf node reconnect.
And I found the leaf node didn't send udp message cause in `simple_udp_sendto` function, the udp_conn is NULL.
```
int
simple_udp_sendto(struct simple_udp_connection *c,
                  const void *data, uint16_t datalen,
                  const uip_ipaddr_t *to)
{
  if(c->udp_conn != NULL) {
    uip_udp_packet_sendto(c->udp_conn, data, datalen,
                          to, UIP_HTONS(c->remote_port));
  }
  return 0;
}
```
Could you tell me the reason and how to fix it?

**Comment by g-oikonomou** [comment]
To the best of my knowledge this should not happen, unless somewhere in your code the UDP connection is getting released when the node leaves the network. Cannot provide more info without seeing the entire code.

Feel free to use gitter for discussions of this nature (unless of course you find something that you think is a bug). Closing for now :)
