### ISSUE TITLE
Stack guard

### ISSUE THREAD

**Issue by atiselsts** [contiki-ng/contiki-ng#104]
See the discussion here: https://github.com/contiki-os/contiki/pull/2089

I can adapt it for Contiki-NG (some work required) and resubmit here. 

The one thing remaining to discuss here: do you have objections against it being enabled by default?
As I stated in the "old" Contiki PR discussion, I believe it would be much more useful if enabled. "Release" builds can always explicitly remove it, by simply adding a compilation flag.

**Comment by g-oikonomou** [comment]
Closed in #192
