### ISSUE TITLE
Cooja build broken with Java 11

### ISSUE THREAD

**Issue by romain-jacob** [contiki-ng/contiki-ng#1046]
Hello there,

I am setting up a fresh install, and notices that building Cooja requires 'java.xml.bind', which (apparently) has been deprecated since JAVA 9 and now completely removed in JAVA 11:
https://stackoverflow.com/questions/52502189/java-11-package-javax-xml-bind-does-not-exist

One can always downgrade to JAVA 10, but that is not great. It would be important to find a proper fix imo. Suggestions welcome.

Cheers,
-- 
Romain

**Comment by mbaddeley** [comment]
I think this is part of the bigger 32-bit issue. As well as supporting later java versions, I think it really needs to be ported to 64-bit machines so it doesn't need to be run on Docker.
________________________________

**Comment by romain-jacob** [comment]
Hum, I do not know whether this has anything to do with the 32- vs 64-bit... One can "fix" the issue by installing java 8 (`sudo apt-get install java-8-openjdk`), then execute the `update-alternative --config java` to select that java8 should be used...

Works, but that's not a great fix I think.

**Comment by iancook1701** [comment]
I have tried installing java 8, and all I get is "E: Unable to locate package java-8-openjdk"

Any thoughts on this? Has anyone gotten it working?

**Comment by alexandruioanp** [comment]
Maybe you need to add the PPA (https://www.geofis.org/en/install/install-on-linux/install-openjdk-8-on-ubuntu-trusty/).

**Comment by iancook1701** [comment]
That did fix the issue I was having, thanks!

**Comment by arurke** [comment]
This seems to have been resolved by https://github.com/contiki-ng/cooja/pull/21
