### ISSUE TITLE
Stats for TSCH and extensions in link stats

### ISSUE THREAD

**Issue by atiselsts** [contiki-ng/contiki-ng#105]
Points for discussion:

- have a stats structure for a single timesource node only, or for each TSCH neighbor? (currently implemented for single only; previous version for each neighbor, but had to drop that because of RAM limitations)
- enabled by default? (currently not)

**Comment by atiselsts** [comment]
I see that there already are big changed in link stats compared to Contiki not-NG. That makes porting my changes in Contiki non-straightforward, so I'll skip that. Also you have `tx_count` and `ack_count` in link stats already, so adding different kind of packet counters (persistent ones) would be confusing.

Will look at TSCH stats next...

**Comment by simonduq** [comment]
So, do we keep this issue open or?

**Comment by atiselsts** [comment]
I plan to contribute the TSCH stats.

**Comment by atiselsts** [comment]
The basic TSCH stats are almost ready from my point of view. But I run into problem when trying to create and example/test program. Sky is not appropriate for this because of `.rom` limitations - even the `simple-node` 6tisch example does not fit on Sky. Cooja mote is not appropriate as its radio does not implement RSSI sampling. Any ideas what to do? Wait for more mspsim platforms or try to improve Cooja?
 
The WIP pull request:
https://github.com/contiki-ng/contiki-ng/compare/develop...atiselsts:contrib/stats

**Comment by simonduq** [comment]
Do you have the example in mind mostly to show the feature or as a CI test or both?

**Comment by atiselsts** [comment]
To show the feature. More importantly, this RSSI reading functionality would be critical for TSCH adaptive channel selection.

Waiting for `exp5438` support to be added back is no problem - good to know that this is moving forward! Perhaps it also makes sense to create a dummy implementation of reading `RADIO_PARAM_RSSI` for Cooja motes, for example, one that returns a constant value. This is what I'm using locally now:

```
diff --git a/arch/platform/cooja/dev/cooja-radio.c b/arch/platform/cooja/dev/cooja-radio.c
index 4f7e6a3..f0dee56 100644
--- a/arch/platform/cooja/dev/cooja-radio.c
+++ b/arch/platform/cooja/dev/cooja-radio.c
@@ -330,6 +330,10 @@ get_value(radio_param_t param, radio_value_t *value)
   case RADIO_PARAM_LAST_LINK_QUALITY:
     *value = simLQI;
     return RADIO_RESULT_OK;
+  case RADIO_PARAM_RSSI:
+    /* return a fixed value depending on the channel */
+    *value = -90 + simRadioChannel - 11;
+    return RADIO_RESULT_OK;
   default:
     return RADIO_RESULT_NOT_SUPPORTED;
   }

```

**Comment by simonduq** [comment]
where are we on this?

**Comment by atiselsts** [comment]
Still waiting for #19. I understand that Michael does not have time to work on in for the near future, so I could look at it and try to make progress when there's time.

**Comment by simonduq** [comment]
can this be closed now with https://github.com/contiki-ng/contiki-ng/pull/637

**Comment by simonduq** [comment]
What's the problem with msp430 platforms, can't you run on Sky with `nullnet`?
