### ISSUE TITLE
Allow to set a different number of MAC retransmissions for each packet

### ISSUE THREAD

**Issue by atiselsts** [contiki-ng/contiki-ng#106]
Enables QoS classes at the network stack & application level. For example, monitoring traffic could be given fewer retransmissions that data collection traffic.

**Comment by atiselsts** [comment]
Been working this today. This is implemented for SPHERE, but in a way that's not general enough, so I thought to redo it properly.

Current ideas are:
* add a new field to `struct uip_conn` and `struct uip_udp_conn`; encourage to set it from application code:
    `uint8_t max_mac_transmissions; /**< Number of max MAC-layer transmissions. */`
* define a new constant `UIP_DEFAULT_MAX_MAC_TRANSMISSIONS`, equal to 0. Meaning: the limit of transmissions is chosen by MAC layer instead - i.e. the current behavior. Use this whenever the application does not tell to do otherwise;
* use the Traffic Class field in IPv6 header to propagate the limit between hosts. Unfortunately, due to the way  6LoWPAN compression works, this means that having a non-zero value in `max_mac_transmissions` field will cause 6LoWPAN headers to grow by 1 byte. An alternative is to only care about the transmission limit at the originating node, and always use the default values when forwarding packets. Perhaps user-configurable choice?

**Comment by simonduq** [comment]
Sounds good. Maybe for generality and for cross-technology contexts, we should not carry the #tx as traffic class, but rather use traffic classes such as 0, 1, 2, that are then mapped to link-layer policies (e.g., setting #tx to some value) at every node.

**Comment by atiselsts** [comment]
Speaking about documentation, I feel this should be documented, but don't immediately see a good place in the Wiki. Suggestions?

**Comment by simonduq** [comment]
Maybe the IPv6 page (which is currently almost empty with just links to some modules, but we should aim for much more content there)

Or under "programming Contiki-NG" somewhere

**Comment by joakimeriksson** [comment]
Check #215 also! I do agree with the model of having traffic class 0,1,2,3,4... etc and then convert that to something matching some kind of QoS per node. But I guess it is fine for now with a bit of a "hack-ish" model (which is what I kept in the PR I did - but moved things up to the IP-layer)?

**Comment by simonduq** [comment]
Wasn't this issue closed by https://github.com/contiki-ng/contiki-ng/pull/182 ?
