### ISSUE TITLE
TSCH calls unsafe functions from interrupt context

### ISSUE THREAD

**Issue by atiselsts** [contiki-ng/contiki-ng#1072]
According to #841, ctimer operations are not safe in interrupt context. However, TSCH manipulates the `keepalive_timer` from `tsch_tx_slot` and `tsch_rx_slot` protothread context. It happens via the `tsch_timesync_update()` and `tsch_schedule_keepalive()` functions.

**Comment by g-oikonomou** [comment]
#1078 fixes this
