### ISSUE TITLE
Energest: add deep sleep mode

### ISSUE THREAD

**Issue by atiselsts** [contiki-ng/contiki-ng#108]
Just an idea for discussion: we have `ENERGEST_TYPE_CPU` and  `ENERGEST_TYPE_LPM` already. Should add something like `ENERGEST_TYPE_DEEP_LPM`. 

For example, on our CC2650 board, the average current values are:
- CPU active: 2.7 mA
- Sleep: 1.3 mA
- Deep sleep: ~0.01 mA (~10 uA)

The difference between deep sleep and sleep is two orders of magnitude. Surely that deserves a different energest class?

**Comment by g-oikonomou** [comment]
Definitely a desirable feature.
