### ISSUE TITLE
Travis fails when Xenial is selected

### ISSUE THREAD

**Issue by yatch** [contiki-ng/contiki-ng#1084]
# Issue
Tests requiring `BUILD_COOJA` fail when Xenial is selected for the test session.

This, https://travis-ci.org/yatch/contiki-ng/builds/594673095, is an example of the issue. The following error stopped the session:

```
$ if [ ${BUILD_COOJA:-false} = true ] ; then ant -q -f $CNG_HOST_PATH/tools/cooja/build.xml jar ; fi
The program 'ant' is currently not installed. To run 'ant' please ask your administrator to install the package 'ant'
The command "if [ ${BUILD_COOJA:-false} = true ] ; then ant -q -f $CNG_HOST_PATH/tools/cooja/build.xml jar ; fi" failed and exited with 127 during .
```

This test was performed against `develop` branch in my personal repository, that points to the head commit of the official `develop` branch. Looking into the build system information, it is found `xenial` was selected.

```
Build system information
Build language: generic
Build group: stable
Build dist: xenial
```

Tests against the same commit in the official repository, https://travis-ci.org/contiki-ng/contiki-ng/builds/591679211, are green. The build system is `trusty`.

```
Build system information
Build language: generic
Build group: stable
Build dist: trusty
```

# Why this happens?
* Xenial has been the default image, but it seems this default switch has not been done completely: https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment
* We don't specify `dist` in our `.travis-ci`; there is a chance Xenial is selected
* The Xenial image doesn't have `ant` installed: https://docs.travis-ci.com/user/languages/java/#using-ant-on-ubuntu-xenial-1604
* Building Cooja fails with the Xenial image because `ant` is missing.

# (short-term) Workaround
Add `dist: trusty` to `.travis-ci`

# Solution
Follow https://docs.travis-ci.com/user/languages/java/#using-ant-on-ubuntu-xenial-1604
```
dist: xenial
language: java
addons:
  apt:
    packages:
      - ant
```

**Comment by yatch** [comment]
Related #1088

**Comment by g-oikonomou** [comment]
Yeap. We are on skype now. We are merging your fix once travis passes.

Thanks!

**Comment by yatch** [comment]
@g-oikonomou :+1:

**Comment by g-oikonomou** [comment]
@yatch why don't you join us on skype if you can? (Timezone permitting!)

**Comment by g-oikonomou** [comment]
Fixed in #1085

**Comment by g-oikonomou** [comment]
PRs against branch `develop` will detereministically fail until #1085 is merged into `develop` too

**Comment by g-oikonomou** [comment]
#1100
