### ISSUE TITLE
CoAP Group Communication (RFC 7390)

### ISSUE THREAD

**Issue by krmal** [contiki-ng/contiki-ng#1091]
Hello,

The features introduced in RFC7390 are not impemented yet, am I correct?

Are these functionalities considered for development in the next Contiki release?

Best Regards,
Krzysztof

**Comment by g-oikonomou** [comment]
They are not implemented, as far as I know.

@joakimeriksson @nfi ?

**Comment by joakimeriksson** [comment]
True, they are not implemented yet. The will not be part of the next 4.4. release coming in a few weeks, and we currently do not have an implementation plan for RFC7390 but we are open to contributions or discussions.
