### ISSUE TITLE
How to port contiki to communicate with cloud?

### ISSUE THREAD

**Issue by mttbx** [contiki-ng/contiki-ng#1094]
Hi, I want to use contiki to both communicate with my other devices and my cloud server. I already have a board with STM32 chip and lan8720A internet phy chip (connect to STM32 MAC controller).  How should I port contiki to my board? 
ps: my board doesn't install linux

**Comment by g-oikonomou** [comment]
Porting guide here: https://github.com/contiki-ng/contiki-ng/wiki/Porting-Contiki%E2%80%90NG-to-new-platforms

Regarding connectivity with a cloud backend, it depends what protocol/technology you want to use. We have some guides on e.g. CoAP, MQTT, LWM2M in the wiki too.
