### ISSUE TITLE
Dynamically use Cache as GPRAM (CC13xx)

### ISSUE THREAD

**Issue by ahmedmibrahim** [contiki-ng/contiki-ng#1095]
Hello, 
This page from TI explains how to use Cache as GPRAM http://dev.ti.com/tirex/explore/content/simplelink_cc13x0_sdk_3_20_00_23/docs/proprietary-rf/proprietary-rf-users-guide/proprietary-rf-guide/cache-as-ram.html

Basically, we need to set a constraint on power during standby, as shown in this section in the page:

`#ifdef CACHE_AS_RAM
// retain cache during standby
Power_setConstraint(PowerCC26XX_SB_VIMS_CACHE_RETAIN);
Power_setConstraint(PowerCC26XX_NEED_FLASH_IN_IDLE);
#else
// Enable iCache pre-fetching
VIMSConfigure(VIMS_BASE, TRUE, TRUE);
// Enable cache
VIMSModeSet(VIMS_BASE, VIMS_MODE_ENABLED);
#endif //CACHE_AS_RAM
`

Where are the equivilant functions for: Power_setConstraint in  c26x0-cc13x0 architecture?

**Comment by g-oikonomou** [comment]
Those constraints are a TI-RTOS thing, we don't use them. You will need to see how those constraints actually affect the power down sequence. Our power management is in `lpm.c` and it is there were we also manage VIMS caching.
