### ISSUE TITLE
Wiki - Documentation SNMP

### ISSUE THREAD

**Issue by Yagoor** [contiki-ng/contiki-ng#1096]
Dear all,

In the wiki-sandbox a simple documentation for the SNMP module is available, [Documentation SNMP](https://github.com/contiki-ng/wiki-sandbox/wiki/Documentation:-SNMP).

This was done according to our gitter conversation, @g-oikonomou. Please, let me know if you want more details or more information.

**Comment by g-oikonomou** [comment]
https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-SNMP
