### ISSUE TITLE
Feature request: OpenMote-B AT86RF215 support

### ISSUE THREAD

**Issue by tinstructor** [contiki-ng/contiki-ng#1102]
Since #1080 now added support for the OpenMote-B node, I think it's a good idea to start working on  support for the AT86RF215 radio chip. Recently, some [interesting work](https://www.mdpi.com/2079-9292/8/9/1045/pdf) has been done with the end-goal of an even more robust TSCH implementation based on OFDM. OpenWSN and RIOT already include drivers or are close to driver adoption. Maybe it is possible to start from the OpenWSN or [RIOT driver](https://github.com/RIOT-OS/RIOT/pull/12128).

**Comment by edgaralb** [comment]
Hello everyone, please help me with the openmote-b drivers for the at86rf215 radio chip for Contiki-ng
