### ISSUE TITLE
Outdated link to MSP430 compiler binaries install script

### ISSUE THREAD

**Issue by krynju** [contiki-ng/contiki-ng#1103]
Link under "this script" for installing compiler binaries was pointing at the [.travis](https://github.com/contiki-ng/contiki-ng/blob/develop/.travis.yml#L24) file which at this point does not contain anything about that . The script for installing the binaries is now located in the [dockerfile](https://github.com/contiki-ng/contiki-ng/blob/develop/tools/docker/Dockerfile#L50).

updated wiki page:
https://github.com/contiki-ng/wiki-sandbox/wiki/Toolchain-installation-on-Linux

**Comment by g-oikonomou** [comment]
Updated. Thanks!
