### ISSUE TITLE
RPL_LOOP_ERROR_DROP is not configurable in rpl-lite

### ISSUE THREAD

**Issue by debug-ito** [contiki-ng/contiki-ng#1105]
In rpl-lite, `RPL_LOOP_ERROR_DROP` macro is used in rpl-dag.c, but this macro is never defined or configurable. Instead, rpl-classic defines its configuration in rpl-conf.h, but it does not use that macro.

I think we should move the configuration of `RPL_LOOP_ERROR_DROP` in rpl-classic/rpl-conf.h to rpl-lite/rpl-conf.h.

**Comment by g-oikonomou** [comment]
Fixed in #1106
