### ISSUE TITLE
cc13x0 deep sleep mode power consumption is still high

### ISSUE THREAD

**Issue by ahmedmibrahim** [contiki-ng/contiki-ng#1131]
Hello, 
I ran the very-sleepy-demo on cc1350 LAUNCHXL, when the device is in deep sleep mode, the current consumption is ~2.5mA which is still pretty high.
- Are there any other modules that are still powered on in the deep-sleep mode?
- How to power them down?

![image](https://user-images.githubusercontent.com/21156993/68918071-98f91f80-0721-11ea-9068-bfc9c41e75b7.png)

**Comment by rajeev1986** [comment]
@ahmedmibrahim, that's because the TSCH scanning thread and the scheduler are still running keeping the MCU active, preventing it from deep sleep. My guess is if you compile the **very-sleepy-demo**  with `MAKE_MAC = MAKE_MAC_NULLMAC` and `MAKE_NET = MAKE_NET_NULLNET` the device power consumption will be in tens of microamps rather than in milli.  However, if you want to keep the default MAC and network running, you will have to explicitly turn off the TSCH before going to deep sleep and turning it back on after waking up.

**Comment by ahmedmibrahim** [comment]
Thanks for your response, 
- I'm not using TSCH at all.
- I tried building with NULLMAC and NULLNET but it failed, do you know how to turn TSCH?

**Comment by ahmedmibrahim** [comment]
@g-oikonomou TI's standby example shows < 10uA of standby current, do you know why the verysleepy demo deepsleep period is consuming ~140uA?

**Comment by ahmedmibrahim** [comment]
@chenek  Do you have any idea how to reduce power here?

**Comment by chenek** [comment]
Try to check you call ext_flash_close to shutdown external flash.

**Comment by ahmedmibrahim** [comment]
Tried turning off ext flash, no change. I think this example doesn't use external flash.
Are there any modules powered on on the MCU itself? I'm just running the demo without any changes.

**Comment by chenek** [comment]
Can you attach a picture of your LAUNCHXL-CC1350 when you measure power consumption?

**Comment by ahmedmibrahim** [comment]
I have verified the setup with TI on this thread
https://e2e.ti.com/support/wireless-connectivity/sub-1-ghz/f/156/t/849367
![image](https://user-images.githubusercontent.com/21156993/70370148-871a2080-1878-11ea-944b-c3ef72829fe2.png)

I get 5.4µA consumption when I ran TI demo (pinStandby) --> I'm confident of my setup

**Comment by chenek** [comment]
Try to keep GND/TX/RX jumpers mounted and test again.

**Comment by ahmedmibrahim** [comment]
NO difference (this will make a difference at lower currents), as I told you, I get 5.4uA using the same setup by just running another example (TI example).

There must be a power module that is still on, this module is not the ext flash (It must be on the MCU itself).

**Comment by chenek** [comment]
Since you use XDS110 on MSP432 launchpad, I think you should connect GND/TX/RX on CC1350 side of LAUNCHXL-CC1350 to XDS110 side of MSP432 launchpad when you do power consumption measurement.

**Comment by ahmedmibrahim** [comment]
Hi @chenek , 
- Do you know what processes are still running in Deep Sleep Mode in this example? 
- Do you know their power consumption?
- Do you know how to turn them off?

**Comment by chenek** [comment]
As I know, there’s o process running during deep sleeping mode. Do you try to remove all jumpers between XDS110 and CC1350, input voltage from 3V3 and GND pins in the bottom of LAUNCHXL-CC1350 and don’t connect JTag to do power measurement?

**Comment by ahmedmibrahim** [comment]
Yes with nothing connected at all (not even the RESET pin) I get ~ 85uA during Deep Sleep Mode
![image](https://user-images.githubusercontent.com/21156993/70397996-c86f1500-19cb-11ea-9cd8-29a0647ca943.png)

Measurement:
![image](https://user-images.githubusercontent.com/21156993/70398016-f5bbc300-19cb-11ea-8a18-722a672363bb.png)

Also sometimes it drops to 2mA only ... any idea why?
![image](https://user-images.githubusercontent.com/21156993/70398037-2865bb80-19cc-11ea-9cbd-14b3b5e4eb95.png)

**Comment by chenek** [comment]
It seems that you use energy trace on MSP432 launchpad to do power measurement. If so, it means you still have JTag connected. I would suggest you to use power analyzer or scope to do power measurement.

**Comment by ahmedmibrahim** [comment]
Ok, do you know why the program drops to a higher current value (~2mA)?

**Comment by chenek** [comment]
I suspect CC1350 wakes up in this case but I am not sure what happens in your case.

**Comment by ahmedmibrahim** [comment]
I think lpm_drop doesn't proceed to deep_sleep_mode, but just the sleep_mode, because a module advertised max_pm supported = LPM_MODE_SLEEP 

I wonder if there is any means to ensure all modules are capable of LPM_MODE_DEEP_SLEEP before calling process_idle()

**Comment by ahmedmibrahim** [comment]
Found it --> I2C Pins are moving randomly up and down (I don't know why), when they are low, more leakage through the pull up Resistors (3.3K).
Leakage = 3.3V / 3.3KOhm x 2 (SDA/SCL) = 2 mA  :)

**Comment by chenek** [comment]
You should set unused pin to PIN_UASSIGNED in your board file.

**Comment by ahmedmibrahim** [comment]
hey @chenek , 
PIN_UNASSIGNED is for simplelink Target,
very_sleepy_demo uses cc26xx-13xx, Can you explain how to do that on this target?
I tried adding pins to BOARD_UNUSED_PINS list in board.h file and it didn't help
I still have some IOs toggling high and low when moving from deep_sleep to active

Also please explain (in detail) how to set the default value of a PIN in Deep_sleep_mode. Example: I want DIO30 to be pulled up in sleep, while DIO25 should be pulled low.

**Comment by chenek** [comment]
I suppose you should set unused pins to PIN_UNASSIGNED in LAUNCHXL-CC1350.h.

**Comment by NeoN7777** [comment]
Hi @chenek 
Do you know what is appropriate power consumption for CC1310 when using TSCH? I have 150-200 uA on a router node, is there any way to reduce the power? Thanks.

**Comment by chenek** [comment]
I think 150-200 uA on a router node is pretty low.

**Comment by NeoN7777** [comment]
> I think 150-200 uA on a router node is pretty low.

So, is there no way to make it 20-40uA with router functions, maybe with some limited abilities?

**Comment by chenek** [comment]
I don’t think so.

**Comment by NeoN7777** [comment]
> I don’t think so.

Okay :(
Thank you

**Comment by ahmedmibrahim** [comment]
A router node cannot go in Deep Sleep mode while routing at the same time
That stand by mode usually consumes ~6-7mA (radio is on, not transmitting), during transmission you will notice current spikes (sudden high current for a very short time) that may reach 22mA (check the datasheet for accurate numbers)

**Comment by ahmedmibrahim** [comment]
BTW, for deep sleep of cc1350 launchpad, 
1- make sure you do JTAG Reset (full reset) after flashing a new image (don't rely on CCS reset) as it gives 100uA leakage
2- my current current consumption is ~8uA in Deep sleep mode (measured with energyTrace) which is still not as the datsheet value (0.7) for cc1350 and 7nA for external Flash

Please let me know if you managed to optimize it further, I desperately need it

**Comment by chenek** [comment]
I think it’s normal to see ~8uA in Deep sleep mode on Launchpad since there are other components on Launchpad. datsheet value (0.7) for cc1350 is CC1350 only and not including other components.

**Comment by ahmedmibrahim** [comment]
I can't see anything else more than the MCU and the Ext Flash... the RF radio should be off and its circuitry.
Anyways, can you answer my question about:

> PIN_UNASSIGNED is for simplelink Target,
very_sleepy_demo uses cc26xx-13xx, Can you explain how to do that on this target?
I tried adding pins to BOARD_UNUSED_PINS list in board.h file and it didn't help
I still have some IOs toggling high and low when moving from deep_sleep to active

> Also please explain (in detail) how to set the default value of a PIN in Deep_sleep_mode. Example: I want DIO30 to be pulled up in sleep, while DIO25 should be pulled low.

**Comment by chenek** [comment]
According to your current power consumption, I think you already set pins correctly.

**Comment by Emirhan-KURU** [comment]
Hello, 
@ahmedmibrahim  @chenek @NeoN7777 

I am working on a project using TI CC1310. It needs to wake up when data comes from the sensor and then go back to sleep mode after sending the data. However, although I have run the examples for Standby and Shutdown modes, the modes do not work properly. When the device goes to sleep mode, the current consumption drops to 0.8 mA, but this value is much higher than expected.

Did you test the sleep mode transition using the sample code, or was there any additional editing done to the code?

![Image](https://github.com/user-attachments/assets/b10b638d-e6db-457a-9f97-6cdf90fcaf40)
The part that is 0.8ma in the picture is the part that goes into sleep mode!
