### ISSUE TITLE
Expired certificate on contiki-ng website

### ISSUE THREAD

**Issue by danadam** [contiki-ng/contiki-ng#1149]
Not sure if this is a correct place to report this but the certificate on https://www.contiki-ng.org expired on 29. October.

**Comment by joakimeriksson** [comment]
Ok, thanks. - I will take a look at it!

**Comment by cb88** [comment]
It's expired still... or again.

**Comment by joakimeriksson** [comment]
Now it is fresh but only valid for contiki-ng.org and not www. I will try to fix that.

**Comment by joakimeriksson** [comment]
Now I think it is correct for www! (finally).
