### ISSUE TITLE
Implementing a custom routing driver

### ISSUE THREAD

**Issue by jeandudey** [contiki-ng/contiki-ng#1153]
I want to implement a custom routing algorithm, however there aren't much explanations of how to do this currently, I've digged a lot in the source code and the route to go is to create a routing driver under the `net/routing` directory, add the proper configuration to the `Makefile.include` (extend it to your algorithm). That's simple, but there isn't any much documentation of how the routing works under the hood, how can one implementa an algorithm that doesn't have a concept of "root" and things like that.

I ask this question in orden to implement an algorithm and possibly help to documentate in the wiki the process needed to create a routing driver.

**Comment by yatch** [comment]
Your routing driver needs to provide the external APIs that are defined in `os/net/routing/routing.h`. Documentation of each APIs and concrete implementations of `rpl-classic` and `rpl-lite` will give you ideas what to be implemented in your routing driver.

Although the core system assumes [RPL](https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-RPL), you may be able to implement something other than RPL.
