### ISSUE TITLE
Need X.509 certificate implementation 

### ISSUE THREAD

**Issue by bismajavid** [contiki-ng/contiki-ng#1168]
Hello,
I am new to research and currently working on X.509 certificates. I need the implementation of the same in Contiki OS. Can someone please help me in this issue? 
Thank you.

**Comment by yatch** [comment]
Generally speaking, X.509 is known to be too heavy for IoT devices. So I think there is little chance someone has an implementation for Contiki-NG project.

**Comment by bismajavid** [comment]
Is there any lightweight implementation of the digital certificates available?
