### ISSUE TITLE
Encryption/Authentication mechanism for RPL in Contiki-ng

### ISSUE THREAD

**Issue by philok93** [contiki-ng/contiki-ng#1172]
Hi all,
I am trying to check if the contiki-ng implements some kind of encryption of the packet payload and header. I am interested in network layer encryption (RPL). Also, authentication is another topic I would like to check if I can implement. Can you please guide me on where to look at or if it's possible to implement AES for example and simulate in Cooja?

Thank you!

**Comment by yatch** [comment]
The link-layer security is implemented, with which you can protect your packets. Regarding AES, you might want to take a look at the following code:

* os/lib/aes-128.[ch]
* os/lib/ccm-star.[ch]
* tests/08-native-runs/07-aes-ccm
