### ISSUE TITLE
How to build Uuid for Zolertia Remote ver b

### ISSUE THREAD

**Issue by YAS-CODE** [contiki-ng/contiki-ng#1174]
Hello Guys,

How i can build Uuid for Zolertia Remote ver b Device using contiki-ng, Any Idea or Sample would be appriciative, Thanks in advance...

br,
Yasir

**Comment by yatch** [comment]
Did you check this wiki page?  https://github.com/contiki-ng/contiki-ng/wiki/Platform-zoul

This README.md gives what you want: https://github.com/contiki-ng/contiki-ng/blob/98c6580e6f1249737235a07caebe68caed250606/examples/platform-specific/zoul/README.md
