### ISSUE TITLE
How to get MAC Address of Zolertia remote

### ISSUE THREAD

**Issue by YAS-CODE** [contiki-ng/contiki-ng#1176]
Hello guys,

I want to get MAC address of REMOTE, Is there any example available to me to test

Thanks,

br,
Yasir

**Comment by yatch** [comment]
Check `linkaddr_node_addr`: https://github.com/contiki-ng/contiki-ng/blob/98c6580e6f1249737235a07caebe68caed250606/os/net/linkaddr.h#L117
