### ISSUE TITLE
Pointer to unknown struct in uip-packetqueue.h

### ISSUE THREAD

**Issue by vprevosto** [contiki-ng/contiki-ng#1186]
While using Frama-C over contiki-ng for the [Vessedia H2020 project](https://www.vessedia.eu), I stumbled upon the definition of `struct uip_packetqueue_packet` in `os/net/ipv6/uip-packetqueue.h`. Namely, its [first field](https://github.com/contiki-ng/contiki-ng/blob/5f1088dd1fd5417960be50f8d792df9d93ed6ba1/os/net/ipv6/uip-packetqueue.h#L9), `next`, is supposed to be a pointer to `struct uip_ds6_queued_packet`, which is apparently neither declared nor defined anywhere in the code base.

Shouldn't the field declaration read `struct uip_packetqueue_packet* next` instead?

**Comment by yatch** [comment]
Interesting ;-) Thank you for reporting this.
