### ISSUE TITLE
Encryption at transport layer

### ISSUE THREAD

**Issue by farid4all87** [contiki-ng/contiki-ng#1187]
Hi, I am doing a project with physical devices where I have 5 CoAP servers and an RPL Border router. Is it possible to implement encryption so the copper browser can see the data but Wireshark can't ? Thanks

**Comment by yatch** [comment]
Use CoAP with DTLS. See https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-CoAP

Or, use the link-layer security (this doesn't provide end-to-end security, though): https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-Communication-Security#link-layer-security
