### ISSUE TITLE
Objective Function implementation help

### ISSUE THREAD

**Issue by philok93** [contiki-ng/contiki-ng#1188]
Hi,
I want to implement my own objective function and I need some help. If anyone knows, how can I modify rpl-mrhof so that I can change the route to choose when a new node joins or when a global repair occurs? I want to introduce a metric that based on the value, each node will belong to a category. For example, 0-5 means average node while 6-10 is a good node and should prefer these nodes.
Also, is it possible to get from link_stats the packets forwarded and packets sent of a node? 
Thank  you!

**Comment by yatch** [comment]
I'm closing this since this is not an issue of contiki-ng. Gitter may be a better place to discuss this kind of thing: Gitter: https://gitter.im/contiki-ng
