### ISSUE TITLE
data analysis in contiki ng

### ISSUE THREAD

**Issue by nilampradhan2** [contiki-ng/contiki-ng#1189]
In contiki OS there was collect view to do performance analysis of protocol. There is no collect view in Contiki-ng, how to do it in contiki-ng? How to plot graph of PDR, latency, duty cycle etc,?
Thank you.

**Comment by yanpads** [comment]
>  How to plot graph of PDR, latency, duty cycle etc,?

You may use the log files. And then you can use [Jupyter Notebook](https://jupyter.org/).

**Comment by nilampradhan2** [comment]
thanks

**Comment by yatch** [comment]
Collect-view is no longer available on contiki-ng (PR #271). As @yanpads suggests, you need to collect log messages, and plot them by yourself.
