### ISSUE TITLE
Can I use memb in contiki?

### ISSUE THREAD

**Issue by mttbx** [contiki-ng/contiki-ng#1192]
Can I use memb in contiki?

**Comment by yatch** [comment]
Yes. See https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-Memory-management#memb-memory-blocks

**Comment by mttbx** [comment]
excellent, thank you!

**Comment by mttbx** [comment]
Sorry, I asked wrong question. Can I use memb in irq?

**Comment by yatch** [comment]
I don't see any issue in using memb in the interrupt context. For sure, you need to take care race conditions. Good luck. https://github.com/contiki-ng/contiki-ng/blob/d736d76847e0632e4acfca6d681165af31eba326/os/lib/memb.c

**Comment by mttbx** [comment]
Thank you!
