### ISSUE TITLE
Help: Implementing clone attack

### ISSUE THREAD

**Issue by philok93** [contiki-ng/contiki-ng#1193]
Hi all,
Does anyone knows how to implement clone attack in contiki and simulate in Cooja?
I tried to play with uip_ds6_addr_add() inside rpl_set_prefix_from_addr in rpl.c and I managed to add global address the same with other node but is not working well. I want to have 2 nodes with the same IP and node id in Cooja. Is this possible?
Thank you!

**Comment by sahel-vafa** [comment]
Hi, 
Please follow the below link. It may be useful.

https://github.com/ecksun/Contiki-IDS/tree/5b93803122c016822241d73ee8f75d537fbd71da/examples/ipv6/rpl-collect
