### ISSUE TITLE
RPL rank of node

### ISSUE THREAD

**Issue by nilampradhan2** [contiki-ng/contiki-ng#1201]
How to access RPL rank of node in orchestra-rule-unicast-per-neighbor-rpl-storing.c file?

Thanks

**Comment by atiselsts** [comment]
The answer depends on whether you use RPL classic or lite. For RPL classic, the function `rpl_get_parent_rank` will find the rank for you if you provide link-layer address.
Or look if you need the rank of the local node RPL instance, look at the `rank` member variable of the `current_dag` member of that RPL instance.
