### ISSUE TITLE
Contiki-NG Getting Started | Documentation Page

### ISSUE THREAD

**Issue by bitvijays** [contiki-ng/contiki-ng#1206]
This could be a [Getting started](https://github.com/contiki-ng/wiki-sandbox/wiki/Contiki-NG-Getting-Started) page

**Comment by ChalinoHu** [comment]
This is my first time to use the CCS with the Contiki-ng,I configured the CCS refer to the document[https://github.com/contiki-ng/contiki-ng/wiki/Platform-simplelink#setup-contiki-ng-in-Code-Composer-Studio]( https://github.com/contiki-ng/contiki-ng/wiki/Platform-simplelink#setup-contiki-ng-in-Code-Composer-Studio)
How to configure the CCS by "Set Program to the absolute path of the generated .elf file. It is recommended to click File System and navigate to the .elf file manually to make sure the path is correct."?
![image](https://user-images.githubusercontent.com/28433380/93706223-ba534500-fb56-11ea-98c2-802ae2d392f3.png)

And I'can't build the project with the console "gmake: *** No rule to make target 'hello-world.elf'.	hello-world		 	C/C++ Problem"
![image](https://user-images.githubusercontent.com/28433380/93706278-2d5cbb80-fb57-11ea-92f7-d2faa5680dbc.png)


Can someone help me?

**Comment by arurke** [comment]
Assuming this is moot after we moved to "Read the Docs" at [docs.contiki.org](https://docs.contiki-ng.org/)
