### ISSUE TITLE
Cooja Configuration Wizard problem(s)

### ISSUE THREAD

**Issue by a1139056159** [contiki-ng/contiki-ng#1207]
Hi,

When I run the cooja configuration wizard, errors occur saying that Can't create file because file doesn't exist (ConifgurationWizard.java: 578). When I read the codes, I found that it is because it tries to create the file but the parent folder doesn't exist.
Therefore, I add a new line before the line 578 to create parent folder:
cLibrarySourceFile.getParentFile().mkdirs();

I'm not sure whether this is the right manner to fix this problem, but it works for me. Hence I post an issue just in case someone may need it.

Best,
Jason

**Comment by rajeev1986** [comment]
Hi @a1139056159,
It seems to me that your COOJA or maybe java home is not configured correctly. After cloning the Contiki-NG repo, make sure to execute the following:
`$ cd contiki-ng`
`$ git submodule update --init --recursive `

Once that is done successfully, navigate to Cooja directly:
`$ cd contiki-ng/tools/cooja`
then run
`$ ant clean`
`$ ant run`

After executing ant run, cooja should startup properly provided that you are on a Linux machine (ubuntu) as cooja does not natively run on macOS. Else you can use docker image to run cooja or virtual machine as outlined [here](https://github.com/contiki-ng/contiki-ng/wiki/Tutorial:-Running-Contiki%E2%80%90NG-in-Cooja).

Hope this helps.
