### ISSUE TITLE
Missing parentheses on define

### ISSUE THREAD

**Issue by nbrunner** [contiki-ng/contiki-ng#1208]
in contiki-ng/os/net/mac/csma/csma.h
CSMA_ACK_WAIT_TIME and CSMA_AFTER_ACK_DETECTED_WAIT_TIME
in contiki-ng/arch/platform/cooja/contiki-conf.h
CSMA_CONF_ACK_WAIT_TIME

**Comment by rajeev1986** [comment]
@nbrunner 
When using #define, parentheses are not actually required per se, but if your compilation is giving errors, then go ahead and add it.

**Comment by nbrunner** [comment]
Lots of whitespace characters are also not actually required, but it's not a reason for not using them.
Currently it's doesn't make a compile or runtime error but it can avoid potential future problem.

**Comment by atiselsts** [comment]
We don't have a coding policy in Contiki-NG that requires parentheses around all define statements, so it not strictly an issue.
