### ISSUE TITLE
How I‌ can have RSSI and EXT neighbor from root node?

### ISSUE THREAD

**Issue by matinpf** [contiki-ng/contiki-ng#1214]
In classic RPL, I want to have EXT and RSSI neighbors in root when receiving DIO‌ in (rpl_process_dio) function.

**Comment by atiselsts** [comment]
The ETX and RSSI of neighbors are stored in link stats.

You can use for example this code to get the link stats entry from the sender:

    struct link_stats *ls = link_stats_from_lladdr(packetbuf_addr(PACKETBUF_ADDR_SENDER));
