### ISSUE TITLE
Running container in distros with cgroup v2

### ISSUE THREAD

**Issue by alexandruioanp** [contiki-ng/contiki-ng#1238]
The `docker run` command in the wiki does not work on Fedora 31. Here is some information: https://medium.com/nttlabs/cgroup-v2-596d035be4d7.

I managed to start it without any kernel changes via podman, with a small tweak (the `userns` parameter was needed to obtain the correct permissions for the mounted folder):
`podman run --userns keep-id --privileged --sysctl net.ipv6.conf.all.disable_ipv6=0 --mount type=bind,source=$CNG_PATH,destination=/home/user/contiki-ng -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v /dev/bus/usb:/dev/bus/usb -ti contiker/contiki-ng`

**Comment by yatch** [comment]
The wiki page is written assuming Ubuntu is used. So, it may not work with other distros as you found.

Thank you for the info, which will be helpful for those who are using Fedora.
