### ISSUE TITLE
Orchestra rule prototypes are missing extern keyword

### ISSUE THREAD

**Issue by hseokman** [contiki-ng/contiki-ng#1249]
When I use native gcc tool, it complains about orchestra rule prototypes.
I see these in the orchestra.h

struct orchestra_rule eb_per_time_source;
struct orchestra_rule unicast_per_neighbor_rpl_storing;
struct orchestra_rule unicast_per_neighbor_rpl_ns;
struct orchestra_rule default_common;

Shouldn't these have extern keyword in front of all of these since it is not declaring these variables here?

**Comment by alexrayne** [comment]
+1

**Comment by g-oikonomou** [comment]
You are right. Flagging this as a bug.

**Comment by atiselsts** [comment]
This is trivial to "fix", but I suspect there was some intention behind this lack of `extern`, so I never did change it. @simonduq should comment.
