### ISSUE TITLE
Multicast example error : Failed to open tun device with root.native

### ISSUE THREAD

**Issue by dpapdpap** [contiki-ng/contiki-ng#1256]
Hi,
I'm new to contiki and I'm trying to run the multicast example (a root to connect to a sink).
In the command line I give `make TARGET = native` and execute `./sink.native`.
It gives me `Failed to open tun device ...` but if I run `sudo./sink.native` it doesn't go wrong.
But if I do `./root.native` or `sudo./root.native` always shows me `Failed to open tun device ...`.
I read somewhere that I need to replace the `native coap package` with the `libcoap`.
I git clone the libcoap [like here](https://libcoap.net/install.html) but the command `make` or `sudo make` gives an error `No targets determined and no makefile found. Stop` but there are `makefile.am, .in, .libcoap`.
Can anyone help me please?

**Comment by g-oikonomou** [comment]
Hi @dpapdpap I don't think you'll be able to run this example using multiple native processes. Suggest running it inside Cooja.

The node coap package and libcoap is a different discussion. I now recommend the latter and depending on what operating system version you should be able to install it without having to compile from sources.
