### ISSUE TITLE
MSF: how to note neigbor about cells are in use?

### ISSUE THREAD

**Issue by alexrayne** [contiki-ng/contiki-ng#1272]
Hallow! i try to start with 6P MSF (that what PR #1000 ).

At present simulation of nodes chain i have regular situation of juming conflict between close pairs :

```
                          <cell:ofs6 ch+3 >  
[node1]             [node2]              [node3]          [node3]
      <cell:ofs5 ch+2>                      <cell:ofs5 ch+2>      <- here conflicts node2-node3!
                     \<-     jumming    ->/

```
1) node1 negotiate cell: offset 5 with node2
2) node2 negotiate cell: offset6 with node3
3) node3 negotiates cell: offset5 with node4, since it is free fr node3
and this situation comes ago next chain nodes.

Does MSF RFC provide any standart ability to reserve cells out from use by neighbors? i.e. node2 somehow protect cell:ofsset5 on node3 ?

**Comment by yatch** [comment]
No. But, if they experience bad performance on the cell at slot offset 5, they will relocate the negotiated cell, which is described by the draft.

> Does MSF RFC provide any standart ability to reserve cells out from use by neighbors?

By the way, this is a question on MSF spec itself. Here is not a right place to ask...
