### ISSUE TITLE
ALIGN EXCEPTION JN5169

### ISSUE THREAD

**Issue by micBona** [contiki-ng/contiki-ng#1275]
Hi everyone, I bought  the NXP® JN516x-EK004 evaluation kit two months ago with two JN5169 devices and after few weeks I decided to flash contiki-ng applications on them. 
**First issue**: I cannot upload the application using Linux. I followed the toolchain at https://github.com/contiki-ng/contiki-ng/wiki/Platform-jn516x but when I tried to install the modified_bootloader as normal application using the normal Windows tool, I got the following output message: "the bootloader is already updated, aborting…". The second way to change the bootloader is to "simply" install the modified one using a JTAG programmer, but no guides or details are provided. Can anyone provide more information?
Finally, I used Windows to flash my devices (using the NXP BeyondStudio software, the JN-SW-4107 JN51xx Production Flash Programmer v1614 and by making some changes to the Makefile.jn516x because the flash programmer set by default is no more available on NXP web site).
**Second issue**: I followed the RPL tutorial (https://github.com/contiki-ng/contiki-ng/wiki/Tutorial:-RPL) flashing both devices with the HelloWorld application with shell enabled and setting one as coordinator and the other one as normal node. They start to exchange RPL messages but after a while, the coordinator receives multiple unicast-DIO messages, generates an ALIGN EXCEPTION and reset itself. I attached the log files.

Has anyone encountered the same problems (especially the second one) ? If yes, How can I fix them?
Thank you in advance.
[CoordinatorLogs.pdf](https://github.com/contiki-ng/contiki-ng/files/4667097/CoordinatorLogs.pdf)
[EndNodeLogs.pdf](https://github.com/contiki-ng/contiki-ng/files/4667098/EndNodeLogs.pdf)

**Comment by nvt** [comment]
This platform was removed recently, so I'm closing the issue.
