### ISSUE TITLE
broadcast unicast in nullnet , same file

### ISSUE THREAD

**Issue by rahimarahul** [contiki-ng/contiki-ng#1278]
Hi, 
I am new in contiki-ng, I want to use unicast and broadcast in same file different process thread using nullnet.  I first call broadcast  and set `nullnet_set_input_callback(input_callback); `  When I try to use different callback  function for unicast. I did not work. Cloud anyone give me any guide line? 

Thanks

**Comment by jansencardoso** [comment]
Hi,

Did you manage to encode this? I have the same problem.
