### ISSUE TITLE
I need help on CoAP example

### ISSUE THREAD

**Issue by dpapdpap** [contiki-ng/contiki-ng#1298]
**EDIT**

I set up a network with a coapClient, a rpl border router and three coap servers (with contiki-ng's examples).
I opened a **tunslip6** το **br** and sent him prefix **abcd :: 1/64**. 
I can do **ping6** at all nodes and with cromium I can see the rb **neighbors** as well as the **routing lings** of the whole network.
With the client I try to send a **service_url** for testing at the node eg **abcd :: 202: 2: 2: 2**. But despite the fact that the client, in the **client_chunk_handler** routine, receives a **response! = NULL** (but empty), the server at this node does not trigger an interrupt but remains permanently in the **PROCESS_WAIT_EVENT ()** command.
What am I doing wrong ?
Can somebody help me please ?
Thanks in advance

**Comment by dpapdpap** [comment]
some help, please ?

**Comment by g-oikonomou** [comment]
Following our discussion on gitter, I am closing this one.
