### ISSUE TITLE
undefined reference to `ble_ipsp_mac_driver' on nrf52dk board

### ISSUE THREAD

**Issue by weizhou-chaojixx** [contiki-ng/contiki-ng#1329]
When I try to compile the coap demo with nrf52dk board and disable SoftDevice support, it cannot be compiled due to undefined reference to `ble_ipsp_mac_driver'.
Did anyone has met this issue before?

**Comment by g-oikonomou** [comment]
As far as I am aware, SoftDevice is required for BLE support.
