### ISSUE TITLE
[MQTT v5] payload_chunk and payload_length include property bytes

### ISSUE THREAD

**Issue by veracl** [contiki-ng/contiki-ng#1341]
I have noticed that the `payload_length` and `payload_chunk` of incoming PUBLISH messages seem to include the property bytes. In my case, no properties are set, so there is only a single zero byte for "Property Length" in front of the actual payload.

```
tcp_input with 84 bytes of data:
MQTT - Read VHDR '30'
MQTT - Read Variable Byte Integer byte 82
MQTT - Finished reading remaining length byte
MQTT - Read PUBLISH topic len 51
MQTT - topic_pos: 0 copy_bytes: 51
MQTT - Got topic '<TOPIC>'
- Copied 29 payload bytes
MQTT - Copied bytes: 
00 31 30 3B 50 55 42 2D 55 50 44 41 54 45 2D 4D 41 4E 49 46 45 53 54 3B 30 2C 41 50 50 
MQTT - Parsing input properties
MQTT - Getting length
MQTT - Read Variable Byte Integer byte 0
MQTT - Received 1 VBI property bytes
MQTT - Input properties length 0
MQTT - First byte of first prop 49

MQTT - Finished reading packet!
MQTT - total data was 83 bytes of data. 
MQTT - First chunk? 1
MQTT - Got PUBLISH, called once per manageable chunk of message.
MQTT - Handling publish on topic '<TOPIC>'
MQTT - This chunk is 28 bytes
[INFO: mqtt-client] Application received publish for topic '<TOPIC>'. Payload size is 29 bytes.
[INFO: mqtt-client] Chunk size is 28 bytes. First chunk: 1
[INFO: mqtt-client] Pub Handler: topic='<TOPIC>' (len=51), chunk_len=28, chunk=''
```

The actual payload is 28 bytes, however, a payload size of 29 bytes and a payload chunk starting with the zero byte get handed to my application (which is why the chunk is incorrectly printed as an empty string).

The chunk size is correct, since the property bytes get subtracted there:

```
        conn->in_publish_msg.payload_chunk_length -= conn->in_packet.properties_len +
          conn->in_packet.properties_enc_len;
```
https://github.com/contiki-ng/contiki-ng/blob/develop/os/net/app-layer/mqtt/mqtt.c#L1442

I believe the same should be done for `payload_length` and `payload_chunk`.

@alexandruioanp

**Comment by alexandruioanp** [comment]
The (unfortunately named) `payload` field in the packet includes both the VHDR and the actual MQTT payload (as per the comment on https://github.com/contiki-ng/contiki-ng/blob/develop/os/net/app-layer/mqtt/mqtt.c#L1410), so I think it being 29 bytes is correct. Maybe we should add something like `conn->in_publish_msg.payload_chunk += conn->in_packet.properties_len + conn->in_packet.properties_enc_len;` at L1456 and L1514.
