### ISSUE TITLE
Does contiki-ng support coap multicast? For instance rfc7390 (Group Communication for the Constrained Application Protocol (CoAP))

### ISSUE THREAD

**Issue by anesh1992** [contiki-ng/contiki-ng#1350]
Hi,
I know there is an example for ipv6 multicast, I was wondering if Contiki-ng has similar any example or support for Coap multicast? Any example code, any plan for future implementation if not implemented?
Thanks!
-Anesh

**Comment by g-oikonomou** [comment]
I had a quick look at the RFC in the title, as far as I can tell the existing multicast support should be sufficient to support most of what's written in there.

There is no off the shelf example for this. To create one, the best starting point would be the existing generic multicast example.
