### ISSUE TITLE
"Bad IL format" when run renode example on windows 10 by using docker image

### ISSUE THREAD

**Issue by policeman0077** [contiki-ng/contiki-ng#1360]
os: windows 10 pro 64bit
docker image: contiker/contiki-ng:latest sha256:6cb428a

when run the rpl-udp example I had following error:
![img](https://i.imgur.com/ZUlXwDe.png)

**Comment by policeman0077** [comment]
https://github.com/renode/renode/issues/43 maybe we should update the renode version in docker image

**Comment by Anshul-99** [comment]
I'm having the same issue. 
OS: Ubuntu 20.04

**Comment by policeman0077** [comment]
> I'm having the same issue.
> OS: Ubuntu 20.04
> 
> Edit: I tried updating the renode version but I'm still facing the same issue.

i installed latest renode natively (instead of docker image) on my Ubuntu 20.04 vm. And now it is working.
