### ISSUE TITLE
Is possible  port simplelink SDK to 4_20_xx_xx?

### ISSUE THREAD

**Issue by GeneKong** [contiki-ng/contiki-ng#1374]
I have tried as guide port Simplelink SDK to 4.20.00.00, but code will stuck at sched.c at netstack_sched_fs at RF_runCmd netstack_cmd_fs. no return and watchdog will timeout.
If we want to try new SDK version, need we update others codes?

**Comment by GeneKong** [comment]
I have test launchpad cc1352r.

**Comment by GeneKong** [comment]
I have compile startup files and case this problem, the source startup file is not complete provide by TI.
Just use library and remove it, case ok.

**Comment by ninjalomaster** [comment]
Hello! does anyone use contiki-ng and simplelink SDK version 5.xx.xx? How to compile contiki-ng with the actual version of the SDK, is there any guide?
we use CC1352.
