### ISSUE TITLE
Toolchain installation guide for OS X

### ISSUE THREAD

**Issue by simonduq** [contiki-ng/contiki-ng#140]
To be added to https://github.com/contiki-ng/contiki-ng/wiki/Toolchain-installation

**Comment by joakimeriksson** [comment]
Should we go for a separate page for this or do different section on the same page?

**Comment by simonduq** [comment]
maybe rather a separate page?

**Comment by g-oikonomou** [comment]
Would have to be a new page now, similar to https://github.com/contiki-ng/contiki-ng/wiki/Toolchain-installation-on-Linux

**Comment by g-oikonomou** [comment]
https://github.com/contiki-ng/contiki-ng/wiki/Toolchain-installation-on-OS-X

@nfi @joakimeriksson feel free to add/edit, but the current version is sufficient for this issue to be closed.
