### ISSUE TITLE
Migration to Python 3

### ISSUE THREAD

**Issue by atiselsts** [contiki-ng/contiki-ng#1453]
Python 2 is end of life and stopped being officially supported in Jan 2020. pip support for Python 2 will be dropped in Jan 2021. This means we should migrate all Python codebase in Contiki-NG to Python3.

Here are potential Python2 dependencies in Contiki-NG at the moment.

1. Scripts that are called by the default Python interpreter at the moment, but probably can be called by Python3 without any code changes:
- [x] <strike>BSL scripts for ARM boards</strike> done in #1448
- [x] `motelist`
- [x] `run-cooja.py` script in `result-visualization` example
- [x] `parse.py` script in `rpl-req-resp` example
- [x] `sensniff` (it looks like it may already support Python3 despite the comment in the source code!)

2. Dependencies:
- [x] Dockerfile (includes pip module installation)
- [x] `tools/vagrant/bootstrap.sh` (includes pip module installation)

3. Scripts that require actual porting effort (only legacy platform stuff here):
- [x] BSL for Z1
- [x] BSL for Sky
- [x] `tools/sky/serial/` (serial dump scripts for Sky and Z1)
- [ ] `tools/jn516x/mote-list.py` (NXP board)

**Comment by g-oikonomou** [comment]
> Scripts that require actual porting effort (only legacy platform stuff here):

What do we want to do with that lot? I am personally not particularly keen on spending effort on those.

**Comment by g-oikonomou** [comment]
motelist: #1465

**Comment by atiselsts** [comment]
Dockerfile and benchmark scripts: https://github.com/contiki-ng/contiki-ng/pull/1552

**Comment by atiselsts** [comment]
Explicitly use Python 2 as discussed: #1558
