### ISSUE TITLE
macOS Contiki Alias

### ISSUE THREAD

**Issue by tallalj** [contiki-ng/contiki-ng#1480]
Hi,

I am following the wiki found at https://github.com/contiki-ng/contiki-ng/wiki/Docker.
The step `prepare contiker alias`. Can you kindly guide me on how to do that? What are we aliasing here?

Furthermore `export CNG_PATH=<absolute-path-to-your-contiki-ng>` The page to Contiki-ng, is this the repo or something else. 

Regards

**Comment by yatch** [comment]
See [this wikipedia article ](https://en.wikipedia.org/wiki/Alias_(command)) for what alias is. Put lines starting "alias contiker=" into ~/.profile or a similar file depending on the shell you're using.

> Furthermore export CNG_PATH=<absolute-path-to-your-contiki-ng> The page to Contiki-ng, is this the repo or something else.

It's the path to `contiki-ng` directory on your machine.
