### ISSUE TITLE
Cann't open cooja of X11 from a container made by contiki-ng 

### ISSUE THREAD

**Issue by onnonn** [contiki-ng/contiki-ng#1484]
I use the paraments 
`docker run --privileged --sysctl net.ipv6.conf.all.disable_ipv6=0 --mount type=bind,source=/Users/onn/contikidocker/contiki-ng,destination=/home/user/contiki-ng -e DISPLAY=host.docker.internal:0 --net=host -v /tmp/.X11-unix:/tmp/.X11-unix -v /dev/bus/usb:/dev/bus/usb -ti contiker/contiki-ng`
and install xquartz and socat which are written in the wiki .
but when I reboot the $DISPLAY of my osx 10.15.7 is empty.
![image](https://user-images.githubusercontent.com/36289793/103440761-6393f600-4c83-11eb-9b07-76a17c914a3a.png)

and then when I run `ant run`
the container shows that 
![image](https://user-images.githubusercontent.com/36289793/103440789-98a04880-4c83-11eb-84f7-5f8e1ea49eda.png)

the socat shell show that
![image](https://user-images.githubusercontent.com/36289793/103440802-a524a100-4c83-11eb-96d1-0daee11a3c25.png)

could u tell me which step is wrong in my shell code?I will appreciate it if u can give me a tip. Looking forward to your reply.

**Comment by yatch** [comment]
Could you try this?
1. Start XQuartz
2. Open "Terminal" from "Applications" on the menu bar (`xterm` will be opened)
3. Run `socat` with the options in the terminal
4. Run `docker run` with the options in a different terminal

**Comment by yatch** [comment]
@onnonn I'm going to close this issue. Feel free to reopen if the issue persists.

**Comment by onnonn** [comment]
> Could you try this?
> 
> 1. Start XQuartz
> 2. Open "Terminal" from "Applications" on the menu bar (`xterm` will be opened)
> 3. Run `socat` with the options in the terminal
> 4. Run `docker run` with the options in a different terminal

when I open XQuartz firstly, then open socat has something wrong like this (maybe the port was used by x11)

![image](https://user-images.githubusercontent.com/36289793/103801669-089a3e80-5089-11eb-8ac0-a9a0126c9cf5.png)

besides that,I have four questions.
1.why the environment variable of macos $DISPLAY is empty after all settings have been done after installing XQuartz?
2.If the $DISPLAY of macos should be set manually, what should be set? The ip of mac or that of the docker container?
 if use the ip of the container , should the docker command value <docker run --net=hosts > be added? Is it possible that docker macos desktop 's UNIX socket is embedded in the middle of the network layer by the virtual sockets file, which leads to this problem?

if you can provide an official setup video tutorial , we will appreciate it greatly！

**Comment by onnonn** [comment]
there is only one success when I try this
 https://superuser.com/questions/1535440/socat-e-connect5-len-4-af-1-0-4-no-such-file-or-directory-when-trying
but when I reboot my mac ，it can never been repeated

**Comment by yatch** [comment]
$DISPLAY should be automatically set. I have no idea why this is not the case on your environment... Better to reinstall XQuartz??

I think, you enable "Allow connections from network clients" in "Security" tab of X11 Preference, which opens by clicking "Preferences..." menu of XQuartz. That's why port 6000 is occupied by X11.bin. Try the steps described above after disabling the setting.

Good luck.

**Comment by yatch** [comment]
@onnonn  any update?

**Comment by yatch** [comment]
If you're using Big Sur, https://www.xquartz.org/releases/XQuartz-2.8.0_beta3.html may be worth a try. Close this for now since it's been inactive.
