### ISSUE TITLE
How can I add new schedular in services folder? Which files i need to modify?

### ISSUE THREAD

**Issue by nilampradhan2** [contiki-ng/contiki-ng#1486]

**Comment by yatch** [comment]
If you're interested in Orchestra, see https://github.com/contiki-ng/contiki-ng/tree/develop/os/services/orchestra

**Comment by nilampradhan2** [comment]
Thanks a lot for immediate reply.
Already i am referring  it, but i want add similar project in contiki. in which all files i need to include it like contiki-main.c etc

**Comment by yatch** [comment]
I think, the fastest way to learn such things is, reading carefully how Orchestra is implemented in Contiki-NG. Good luck.

**Comment by nilampradhan2** [comment]
Thank you for your suggestion.
