### ISSUE TITLE
switch to parent NULL when UIP_CONF_ND6_SEND_NS=1 with RPL-lite

### ISSUE THREAD

**Issue by damien-v** [contiki-ng/contiki-ng#1498]
I have a cooja setup where RPL lite is enabled and
`UIP_CONF_ND6_SEND_NS=1`
When a node is set as root, the other nodes join the rpl instance as expected but after some time the network stops working. Nodes loose the preferred parent for some time and re-join again. 

I used the hello-world example and enabled the shell, rpl lite and the UIP_CONF_ND6_SEND_NS flag. 5 nodes, linear setup each in range of one neighbor on each side. Root node on the far left. The mote output log is attached here (ID 3 is 1 hop from the root and has RPL logging enabled):

[loglistener_append.txt](https://github.com/contiki-ng/contiki-ng/files/5905684/loglistener_append.txt)

Then it cascades and gets worse and worse the deeper in the network, because DAO-ACK's are not received due to broken links on the way.

The interesting parts are switch to parent NULL, e.g.

```
[INFO: RPL       ] parent switch: fe80::201:1:1:1 -> (NULL IP addr)
```

I have a branch reproducing this issue: https://github.com/damien-v/contiki-ng/tree/issue-rpl-lite-with-send-ns

**Comment by atiselsts** [comment]
I agree, this is a bug in Contiki/Contiki-NG RPL implementation.

@simonduq @joakimeriksson could you look at this?
I think the main proble is that the RPL code threats neighbors with `state != NBR_REACHABLE` as unreachable. While in fact it just means that either "the neighbor is no longer known to be reachable" or that the reachability has not yet been determined (https://tools.ietf.org/html/rfc4861). In fact, the states PROBE and DELAY mean the reachability is in the process of being determined.

Perhaps in the best parent selection we should just apply the same logic as when checking if the neighbor is fresh? That is to say, in the `best_parent()` function allow to select parent with unknown reachability if `fresh_only == false`.
