### ISSUE TITLE
simple-udp.c: client_process is never set

### ISSUE THREAD

**Issue by kluchsinger** [contiki-ng/contiki-ng#1510]
In simple-udp.c, the process context is set to client_process right before calling the receive_callback:
[see here](https://github.com/contiki-ng/contiki-ng/blob/48a3799e2d2c52e91cb7153b163bb26dfd9a4b4f/os/net/ipv6/simple-udp.c#L163)

However, client_process is not set anywhere.

If I understand it correctly, it should be set in simple_udp_register():
`c->client_process = PROCESS_CURRENT();`

Or am I misunderstanding something here?

**Comment by damien-v** [comment]
I think you are correct. Maybe submit a pull request and hopefully someone with sufficient rights will have look at it?

**Comment by nvt** [comment]
Thanks for reporting this issue -- it has now been fixed.
