### ISSUE TITLE
Cooja: print RTIMER_NOW() with string，something funny appear

### ISSUE THREAD

**Issue by StarUnderNight** [contiki-ng/contiki-ng#1527]
在cooja上做仿真时，用printf打印了RTIMER_NOW()这个时间，如下
        char log_buf[LOG_LINE_LEN];
	memset(log_buf, 0, LOG_LINE_LEN);

	char ip_buf[UIPLIB_IPV6_MAX_STR_LEN];
	uiplib_ipaddr_snprint(ip_buf, UIPLIB_IPV6_MAX_STR_LEN, addr);

	sprintf(log_buf + strlen(log_buf), "%s-", ip_buf);
	int i = 0;
	for (; i < len; i++) {
		sprintf(log_buf + strlen(log_buf), "%02x ", data[i]);
	}

	char test[] = {'a','b','c','d','e'};
	uint32_t now = RTIMER_NOW();
	printf("time = %d,%s\n",now,test);
	printf("time = %d,%s\n",RTIMER_NOW(),test);
	printf("test = %s\n",test);
其中，addr是一个ipv6地址，LOG_LINE_LEN长度是500，data是一个字符数组，可以忽略它。
我打印结果如下：
26:38.436	ID:1	time = 1598436000,abcdefd00::202:2:2:2
26:38.436	ID:1	time = 1598436000,(null)
26:38.436	ID:1	test = abcdefd00::202:2:2:2

**Comment by damien-v** [comment]
try
```c
char test[] = {'a','b','c','d','e', 0};
```
