### ISSUE TITLE
Dockerimage - libusb-1.0-0 package missing

### ISSUE THREAD

**Issue by warner83** [contiki-ng/contiki-ng#1536]
Hello, it looks like that the package libusb-1.0-0 is missing. That is an issue to flash NRF52840-dongle.
Running the command:
sudo apt install libusb-1.0-0
on the docker image solves the issue.

**Comment by atiselsts** [comment]
Thanks for the report, we can probably simply add it the command https://github.com/contiki-ng/contiki-ng/blob/develop/tools/docker/Dockerfile.
