### ISSUE TITLE
Simulate CoAP Server and BR in Cooja

### ISSUE THREAD

**Issue by fkerem** [contiki-ng/contiki-ng#1546]
I could not find any mote to simulate coap server in Cooja.
I tried all motes and they did not compile.
Do you have any suggestions?

**Comment by jeppenodgaard** [comment]
Whats your environment and what is you compile error?

Building examples/coap/coap-example-server/ with `make -j coap-example-server.cooja TARGET=cooja` in docker image contiker/contiki-ng should work.

**Comment by atiselsts** [comment]
I suggest following jeppenodgaard's advice. Let us know if there are futher questions.

**Comment by fkerem** [comment]
I use the docker image for Mac.
Here is the compilation output I get when I use the command that you provided @jeppenodgaard

`
> make -j coap-example-server.cooja TARGET=cooja MAKE_ROUTING=MAKE_ROUTING_RPL_CLASSIC 
  CC        coap-example-server.c
  MKDIR     build/cooja/obj
  CC        ../../../arch/platform/cooja/./platform.c
  CC        ../../../arch/platform/cooja/lib/simEnvChange.c
  CC        ../../../arch/platform/cooja/sys/cooja_mt.c
  CC        ../../../arch/platform/cooja/sys/cooja_mtarch.c
../../../arch/platform/cooja/./platform.c:38:10: fatal error: jni.h: No such file or directory
 #include <jni.h>
          ^~~~~~~
compilation terminated.
make: *** [platform.o] Error 1
../../../Makefile.include:412: recipe for target 'platform.o' failed
make: *** Waiting for unfinished jobs....
  CC        ../../../arch/platform/cooja/./rtimer-arch.c
Process returned error code 2
`

Appreciate your help!

**Comment by fkerem** [comment]
No, even though I pulled the latest Docker image, I get the same compilation error:

`
> make coap-example-server.cooja TARGET=cooja 
  CC        coap-example-server.c
  MKDIR     build/cooja/obj
  CC        ../../../arch/platform/cooja/./platform.c
../../../arch/platform/cooja/./platform.c:38:10: fatal error: jni.h: No such file or directory
 #include <jni.h>
          ^~~~~~~
compilation terminated.
make: *** [platform.o] Error 1
../../../Makefile.include:412: recipe for target 'platform.o' failed
Process returned error code 2
`

**Comment by fkerem** [comment]
Can this be the case?

https://github.com/contiki-ng/contiki-ng/issues/1224#issuecomment-613673076


My JAVA_HOME env variable is pointing to `/usr/lib/jvm/java-8-openjdk-i386/`.
