### ISSUE TITLE
Why mentionning emacs in toolchain ?

### ISSUE THREAD

**Issue by sieben** [contiki-ng/contiki-ng#162]
https://github.com/contiki-ng/contiki-ng/wiki/Toolchain-installation Why does this page mention emacs?

**Comment by joakimeriksson** [comment]
Because some of us have been using emacs for development - any other editor would work also! Any suggestions that you would prefer?

**Comment by sieben** [comment]
No editor at all. 😃 People can install a new one if they want to. Plus it
avoids flame wars.

Le mer. 8 nov. 2017 07:54, Joakim Eriksson <notifications@github.com> a
écrit :

**Comment by joakimeriksson** [comment]
Ok, so writing "apt get install <YOUR-FAVORITE-EDITOR>" is what we need ;-)

**Comment by joakimeriksson** [comment]
Moved away emacs from the install list now. Ok?

**Comment by sieben** [comment]
yup :)

**Comment by simonduq** [comment]
👍
