### ISSUE TITLE
Invalid link_stats RSSI value

### ISSUE THREAD

**Issue by jeppenodgaard** [contiki-ng/contiki-ng#1629]
If a neighbor is added automatically (UIP_ND6_AUTOFILL_NBR_CACHE needs to be enabled) because it is not in the nbr table, the RSSI value seems to set to 0.

This is not an issue at first because link_stats_from_lladdr() returns NULL.

However when the neighbor replies the RSSI value is updated and link_stats_from_lladdr() returns a pointer and the RSSI value is averaged with the invalid RSSI value 0.

The issue can be reproduced by checking out [this repo/branch](https://github.com/jeppenodgaard/contiki-ng/tree/bug/invalid-link-stats-rssi-value) and open and run tests/test-link-stats-rssi.csc in cooja.

**Comment by atiselsts** [comment]
Thanks for the detailed report, I agree with the problem description. We'll create a fix.
