### ISSUE TITLE
Contiki-ng logo

### ISSUE THREAD

**Issue by remyleone** [contiki-ng/contiki-ng#163]
That would be a killer feature compared to contiki :)

**Comment by simonduq** [comment]
This planned yes, we will have a logo by the next release (which is due
next spring)!

**Comment by simonduq** [comment]
This was put on hold for a number of reasons. Pushing to next release.

**Comment by simonduq** [comment]
Pushing once again.

**Comment by joakimeriksson** [comment]
Logo is currently being designed and we have a few suggestions. So hopefully this will be part of the next release!

**Comment by simonduq** [comment]
Will be announced soon
