### ISSUE TITLE
Native toolchain installation - mac- m1

### ISSUE THREAD

**Issue by vinobc** [contiki-ng/contiki-ng#1669]
brew tap caskroom/cask     //brew tap homebrew/cask worked 
$ brew cask install tuntap //cmd. is brew install --cask tuptap
                                            //but does not work on mac m1
i get :

==> Purging files for version 20150118 of Cask tuntap
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=vinob USER=vinob USERNAME=vinob /usr/sbin/installer -pkg /opt/homebrew/Caskroom/tuntap/20150118/tuntap_20150118.pkg -target /` exited with 1. Here's the output:
installer: Package name is TunTap Installer package
installer: Installing at base path /
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “tuntap_20150118.pkg”.)

**Comment by alexstanoev** [comment]
Hi,

tuntap is not a required dependency and is not supported on M1, you can safely skip it.
You will not be able to use the native target with networking, however tunslip6 will still work.
