### ISSUE TITLE
Orchestra and fragmented packets

### ISSUE THREAD

**Issue by e120guru** [contiki-ng/contiki-ng#168]
It would be really handy with a good way of scheduling a listening (and transmitting) slot immediately if the IPv6 packet was fragmented by 6lowpan layer and there is more fragments to send... This really would make a huge difference in our low duty cycle leaf nodes.

@simonduq and @joakimeriksson mentioned that this might be up for consideration in a standardisation work of Orchestra... Is, and in that case when, would that be of for grabs?

**Comment by simonduq** [comment]
Well, you are spot-on. The current draft is at:
https://tools.ietf.org/html/draft-duquennoy-6tisch-asf-00

And based on the feedback at IETF99, we will add two things:
* define how to configure the schedule at bootstrap
* add support for traffic bursts, e.g. fragmented 6lowpan

The way we currently plan to support bursts is to use the IEEE 802.15.4 header "frame pending" bit to signal that there is more traffic to come. Upon receiving a unicast with this bit set, the receiving node will  automatically schedule the next slot for Rx. This goes on until a packet is received with the bit unset, or until there is a packet loss.

Labeling as `roadmap` as this is on our list!

Thanks!

**Comment by simonduq** [comment]
Please take a look at https://github.com/contiki-ng/contiki-ng/pull/380 and let us know if this works for you!
