### ISSUE TITLE
radio frequency when running "examples/rpl-udp"

### ISSUE THREAD

**Issue by mycstudy** [contiki-ng/contiki-ng#1696]
hello,
Does anyone know that when the demo "examples/rpl-udp" is run on the cc1350, the radio frequency on the physical layer will use 2.4GHz or not? Because I also use other devices that work at 2.4GHz, I hope there is no interference between them.

**Comment by alexrayne** [comment]
freq depensd on platform, you build for. On `cc26x0-cc13x0` examine setup `DOT_15_4G_FREQUENCY_BAND_ID`

**Comment by mycstudy** [comment]
hi alexrayne, thank you a lot! I spent a lot of time in order to find it.
