### ISSUE TITLE
MPL driver doesn't correctly handle multicast address flags

### ISSUE THREAD

**Issue by edrose** [contiki-ng/contiki-ng#1700]
IPv6 multicast addresses have the format `FFXX::` where the first `X` is a set of flags, and the second `X` is the scope. The MPL implementation doesn't correctly split the second byte of an IPv6 multicast address into `flags` and `scope`, and instead treats the entire second byte as the scope. One of the flag bits is set to indicate that the address is a dynamically assigned address, rather than a well-known address.

This means that the MPL implementation can only currently be used with multicast addresses where the flag bits are cleared, and it  forces users to break the multicast address specification if they want to use a multicast address other than the well-known MPL "All Forwarders" address `FF0X::FC`.

---

I think this only appears in three places in the driver, most notably at [`mpl.c:462`](https://github.com/contiki-ng/contiki-ng/blob/develop/os/net/ipv6/multicast/mpl.c#L462):

```lang=c
#define UIP_ADDR_MAKE_LINK_LOCAL(a) (((uip_ip6addr_t *)a)->u8[1] = UIP_MCAST6_SCOPE_LINK_LOCAL)
```

It's also an issue in [`mpl.c:537`](https://github.com/contiki-ng/contiki-ng/blob/develop/os/net/ipv6/multicast/mpl.c#L538), and [`mpl.c:538`](https://github.com/contiki-ng/contiki-ng/blob/develop/os/net/ipv6/multicast/mpl.c#L538) where the whole byte is used in a scope comparison.

@g-oikonomou

**Comment by nvt** [comment]
Closing the issue because this has now been fixed in #1702. Thanks!
