### ISSUE TITLE
typo: wiki/packet-buffers

### ISSUE THREAD

**Issue by drac98** [contiki-ng/contiki-ng#1712]
I think there is a typo in the end of the wiki of [Packet Buffers](https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-Packet-buffers#queuebuf)
"""
Keep in mind that some Contiki-NG features strictly need the queuebuf module (e.g. CSMA, TSCH, 6LoWPAN fragmentation support), so you should only try to disable it if you do need any of this functionality.
"""
The last line should read as `do not need` instead of `do need`

**Comment by nvt** [comment]
Thanks, it has now been fixed.
