### ISSUE TITLE
Openmote missing in Cooja

### ISSUE THREAD

**Issue by LeoLee0097** [contiki-ng/contiki-ng#1715]
Dear all
Am I missing something? I saw that Contiki-os/Contiki-ng supports the Openmote/Openmote B, but why I could not see them in the Cooja mote list?
Similar Q for Contiki-OS: https://github.com/contiki-os/contiki/issues/2663

**Comment by alexrayne** [comment]
cooja uses special contiki target for it's simulations. openmote - target
on hardware platform. so, you simulate on cooja-target, and provide
binaries for hardware on according target - openmote

вс, 2 янв. 2022 г., 12:31 Leonard ***@***.***>:

**Comment by LeoLee0097** [comment]
@alexrayne, I appreciate your reply, it helped me a lot, and I think it's time to close this issue now.

**Comment by atiselsts** [comment]
If you need ARM hardware simulations, look into Renode, it's also supported by Contiki-NG.

Otherwise follow Alex's advice.

Closing the issue now.
