### ISSUE TITLE
Set transmission power for NRF5340

### ISSUE THREAD

**Issue by iliar-rabet** [contiki-ng/contiki-ng#1732]
Hi,

I am trying to change the transmission power of the NRF5340 devices (for IEEE 802.15.4 radio) with Contiki-NG.
With some other hardware (sky motes) that is based on CC2420 radio Contiki uses a function like this:

```
static void
set_txpower(uint8_t power)
{
  uint16_t reg;

  reg = getreg(CC2420_TXCTRL);
  reg = (reg & 0xffe0) | (power & 0x1f);
  setreg(CC2420_TXCTRL, reg);
}

```
Obviously, NRF is not using CC2420 so this function is not working.
I wonder if there is a way to do that for NRF5340?

Bests,
Iliar

**Comment by alexstanoev** [comment]
You can set the TX power using the `RADIO_PARAM_TXPOWER` parameter, i.e. something like:
```
NETSTACK_RADIO.set_value(RADIO_PARAM_TXPOWER, (radio_value_t) RADIO_TXPOWER_TXPOWER_0dBm);
```

You will need to include `netstack.h`.

**Comment by iliar-rabet** [comment]
Thanks very much.

**Comment by iliar-rabet** [comment]
Hi @alexstanoev,

When I call `NETSTACK_RADIO.set_value` I get no compile error but nothing is shown on the serial and packets are not sent  
But when I comment out the `NETSTACK_RADIO.set_value` the packets are sent with no problem and the logs are printed on the serial connection.

Here is the setting:
For the network core, I call the function `NETSTACK_RADIO.set_value(RADIO_PARAM_TXPOWER, (radio_value_t) RADIO_TXPOWER_TXPOWER_0dBm);` in the link-stat.c after each packet being received.
I am running examples/rpl-udp/udp-client.c
For compilation I use: make TARGET=nrf BOARD=nrf5340/dk/network udp-client.upload

```
nrfjprog -f NRF53 --coprocessor CP_NETWORK   --sectorerase --program build/nrf/nrf5340/dk/network/udp-client.hex
Parsing image file.
WARNING: A programming operation has been performed without --verify.
WARNING: Programming can fail without error.
nrfjprog -f NRF53 --coprocessor CP_NETWORK   --reset
Applying system reset.
Run.

```

For the application core, I use the [Zephyr empty firmware] (https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/samples/nrf5340/empty_app_core/README.html#nrf5340-empty-app-core) by the command west flash.

```
-- west flash: rebuilding
ninja: no work to do.
-- west flash: using runner nrfjprog
There are multiple boards connected.
1. 960136292
2. 960186287
Please select one with desired serial number (1-2): 2
-- runners.nrfjprog: Flashing file: /home/iliar/ncs/nrf/samples/nrf5340/empty_app_core/build/zephyr/zephyr.hex
Parsing image file.
WARNING: A programming operation has been performed without --verify.
WARNING: Programming can fail without error.
Applying pin reset.
-- runners.nrfjprog: Board with serial number 960186287 flashed successfully.

```

**Comment by alexstanoev** [comment]
I cannot reproduce this on an nRF5340-DK using examples/hello-world and examples/platform-specific/nrf/start-network-core.

I have tried calling both `NETSTACK_RADIO.set_value(RADIO_PARAM_TXPOWER, (radio_value_t) RADIO_TXPOWER_TXPOWER_Neg4dBm);` and `NETSTACK_RADIO.set_value(RADIO_PARAM_TXPOWER, (radio_value_t) RADIO_TXPOWER_TXPOWER_0dBm);` and the network core runs successfully in both cases.

Could you attach a debugger to the network core and see if it's faulting somewhere?
