### ISSUE TITLE
OpenMoteB flash

### ISSUE THREAD

**Issue by hongseokwonx** [contiki-ng/contiki-ng#1764]
Openmote-b is flashed as an RPL-UDP example, and it initially flashes, but from the second time 0x55 comes out and does not flash. Is there a solution?

**Comment by LeoLee0097** [comment]
Hi @[hongseokwonx](https://github.com/hongseokwonx)

I encountered the same issue as you mentioned here (https://github.com/contiki-ng/contiki-ng/issues/2117). Could you please tell me how you solved this issue?

Best regards
Leo
