### ISSUE TITLE
Broken links on Wiki page Organization 

### ISSUE THREAD

**Issue by zhitaoh** [contiki-ng/contiki-ng#1771]
I want to check out who currently make up the maintainers and the board on https://github.com/contiki-ng/contiki-ng/wiki/Organization

But the following two links are broken:
"Contiki-NG has a group of [maintainers](https://github.com/orgs/contiki-ng/teams/maintainers/members), a subset of which constitutes the [board](https://github.com/orgs/contiki-ng/teams/board/members)."

**Comment by atiselsts** [comment]
Hi, the links work for me. If I'm logged in from my account, I get taken to the respective pages. If I'm not logged in, I got taken to Github login page.

Perhaps there is some access / visibility issue here?

**Comment by zhitaoh** [comment]
I looked at them once again. Apparently the "broken" URLs are under the _teams_ directory, instead of _wiki_. That might explain why Atis you as a merge team member can access them, but I cannot. If this is supposed to be public info, then I suggest copying it to the wiki.
