### ISSUE TITLE
Platform NRF Documentation

### ISSUE THREAD

**Issue by Yagoor** [contiki-ng/contiki-ng#1792]
Hi All,

I realised that I never submitted the wiki page for the nrf port. (Or at least I could not find it)

[Platform-nrf.md](https://github.com/contiki-ng/contiki-ng/files/8502215/Platform-nrf.md)

**Comment by alexstanoev** [comment]
Thanks, I've added it to the wiki under [Platform-nrf](https://github.com/contiki-ng/contiki-ng/wiki/Platform-nrf) :)
