### ISSUE TITLE
Serial input on CC1310 Launchpad

### ISSUE THREAD

**Issue by mike-forster** [contiki-ng/contiki-ng#187]
Running through the NG Shell tutorial  on a C1310 Launchpad serial input doesn't work. It needs the line 
`  cc26xx_uart_set_input(serial_line_input_byte);`
added after
`  serial_line_unit();` in platform_init_stage_two in platform.c

The terminal program also needs to send CR+LF at the end of the line

**Comment by g-oikonomou** [comment]
Thanks Mike,

I can confirm this as a bug and it will affect all CC13xx/CC26xx platforms/boards: Serial shell will be non-responsive.

Unless we explicitly request UART RX (by passing a non-NULL function pointer to `cc26xx_uart_set_input()`), the platform code turns the UART off very aggressively to reduce energy consumption. As a result, keystrokes on the terminal are not getting received by the serial shell code.

This is the diff for a temporary fix:
```
$ git diff
diff --git a/arch/platform/srf06-cc26xx/platform.c b/arch/platform/srf06-cc26xx/platform.c
index 7b8a8c477..964e4da0b 100644
--- a/arch/platform/srf06-cc26xx/platform.c
+++ b/arch/platform/srf06-cc26xx/platform.c
@@ -55,6 +55,7 @@
 #include "vims.h"
 #include "dev/cc26xx-uart.h"
 #include "dev/soc-rtc.h"
+#include "dev/serial-line.h"
 #include "rf-core/rf-core.h"
 #include "sys_ctrl.h"
 #include "uart.h"
@@ -167,6 +168,7 @@ platform_init_stage_two()
 #endif
 
   serial_line_init();
+  cc26xx_uart_set_input(serial_line_input_byte);
 
   /* Populate linkaddr_node_addr */
   ieee_addr_cpy_to(linkaddr_node_addr.u8, LINKADDR_SIZE);
```
