### ISSUE TITLE
Re-add exp5438

### ISSUE THREAD

**Issue by simonduq** [contiki-ng/contiki-ng#19]

**Comment by simonduq** [comment]
Assigning to next release

**Comment by joakimeriksson** [comment]
Is anyone working with this right now? We need to get this started in a month so that it is done by the milestone deadline.

**Comment by atiselsts** [comment]
I'm wondering that as well, and whether I should continue to wait for this so I can submit my TSCH stats code complete with regression tests (Issue #105)
@g-oikonomou?

**Comment by mbaddeley** [comment]
I actually have this done - it works, but it's not in a mergeable state at the moment. As well as needing to be rebased to develop to get in the latest changes it also needs to be more in-line with the other platform types. Currently a lot of the code is copied straight from Contiki, without having put everything into a platform.c file.


https://github.com/mbaddeley/contiki-ng/tree/contrib/re-add-exp5438

________________________________

**Comment by mbaddeley** [comment]
I've re-based and it still compiles, but I get a cooja java.lang.ArrayIndexOutOfBounds error when I run now. Don't have time to look at this at the moment but if anyone else wants to pick it up I have it on github [here](https://github.com/mbaddeley/contiki-ng/tree/contrib/re-add-exp5438)

**Comment by mbaddeley** [comment]
Ok, so looking back at previous commits, the last commit that my exp5438 code was working for was 58f9d2bc0adc018b8db3cd227fd158f67b53b78e

If you check out that, and cherry pick commit a6608f57b0c96614a19961812df42f4e5930554e from my contrib branch everything compiles and runs ok in cooja.

**Comment by atiselsts** [comment]
Are we still on track for including this in 4.1?

**Comment by simonduq** [comment]
Ping

**Comment by simonduq** [comment]
Postponing to 4.2

**Comment by atiselsts** [comment]
I tried to finish this exp5438 Contiki-NG platform port. So far no luck - got some strange watchdog lockups. I think I'll give up on this.

Maybe the problem was that I tried to port TSCH to exp5438 at the same time. (I just today realized that TSCH does not run on exp5438 out of the box, since SFD capture is not working due to different pin layout.) Ended up spending some time remapping the timers to Timer B to free Timer A0 for the SFD - should be working in theory (but not in practice, as said above).

**Comment by mbaddeley** [comment]
Your fixes seem to be working for CSMA, however :)

**Comment by simonduq** [comment]
What do we do with that one, postpone once more or just mark as long-term for now?

**Comment by atiselsts** [comment]
I think we should drop this idea, as Z1 seems to be serving well enough in the role, and also because adding the exp5438 port would take significant effort.

Additionally, the Cooja mote is massively improved since this issue was made, now covering most of the simulation-only use cases.

**Comment by mbaddeley** [comment]
As someone who used to use it quite a lot - I completely agree. The cooja
note is more than enough IMO in terms of what the cooja exp implementation
was being used for.
