### ISSUE TITLE
Wiki/Vagrant: bootstrap.sh should not be run with sudo

### ISSUE THREAD

**Issue by pjonsson** [contiki-ng/contiki-ng#1962]
The Vagrant documentation on the Wiki (https://github.com/contiki-ng/contiki-ng/wiki/Vagrant) lists the command:
```
$ sudo ./contiki-ng/tools/vagrant/bootstrap.sh
```
The individual commands inside bootstrap.sh that need root permissions use sudo, so the sudo when calling the script should be removed.

**Comment by nfi** [comment]
Fixed via #2024.
