### ISSUE TITLE
Don't disable the CC13xx/CC26xx Debug Interface by default

### ISSUE THREAD

**Issue by g-oikonomou** [contiki-ng/contiki-ng#200]
`ccfg.c` in CC13xxware/CC26xxware disables the debug interface by default. This is the result of a change in each of the two respective submodules (contiki-os/cc26xxware#1 and contiki-os/cc13xxware#1).

While these changes make absolute sense, they are also causing a lot of inconvenience: Programming a CC13xx/CC26xx device with any firmware that includes these changes locks down the device. It can neither be programmed again nor erased over the debug interface without first doing a forced mass erase from Flash Programmer 2. There does not appear to be an easy way to do a forced mass erase through UniFlash and this therefore causes problems for non-Win users.

What we want to do is to introduce a new configuration directive that can enable/disable the debug interface through `contiki-conf.h`, in a fashion similar to what we are doing for the ROM bootloader.

**Comment by fontikos** [comment]
+1

Also, it should, perhaps, be highlighted in a comment that disabling the debug interface is more secure for deployed images.
