### ISSUE TITLE
CoAP not parsing options

### ISSUE THREAD

**Issue by AntonioLangiu** [contiki-ng/contiki-ng#207]
I noticed that the CoAP implementation is not parsing the received options.

After some debugging, I found out that during the refactor of er-coap [this line](https://github.com/contiki-ng/contiki-ng/blob/develop/os/net/app-layer/coap/coap.c#L547) was added in the`coap_parse_message` function. Removing that line fixes the problem.

**Comment by joakimeriksson** [comment]
Thanks for the report. That certainly looks like a bug. We are currently working on a big PR with CoAP, LWM2M and DTLS and we will ensure that this bug is fixed when that gets in (or even before as a separate fix-PR).

**Comment by AntonioLangiu** [comment]
Thank you! 👍

**Comment by simonduq** [comment]
addressed in https://github.com/contiki-ng/contiki-ng/pull/210

**Comment by joakimeriksson** [comment]
and now #210 is in - @AntonioLangiu: I guess this can be closed ?

**Comment by AntonioLangiu** [comment]
Yes, it can be closed! Thank you for the fast merge!
