### ISSUE TITLE
Cooja Mote: Mote type creation error

### ISSUE THREAD

**Issue by YSmolders** [contiki-ng/contiki-ng#2258]
Hi all, 

I'm experiencing trouble while trying to create a Cooja mote in the cooja environment.

Im on the latest Contiki-ng release,  which is 4.8 and have updated all the submodules. 
Running on Ubuntu. 
I have tried with installing java 17 myself and using the Docker image, both give the same result. 

When creating a Cooja mote, e.g. the hello-world.c example I get the errors as shown below. 

Z1 motes run fine, btw.
![error](https://user-images.githubusercontent.com/58876359/200335151-f6c043ea-0388-4a74-9016-84e8120e596c.png)
![error1](https://user-images.githubusercontent.com/58876359/200335167-f448c1da-e4db-42eb-b5e5-d095127a2572.png)

**Comment by pjonsson** [comment]
This error scenario should be impossible in the latest Cooja master branch, but I don't think the submodule in Contiki-NG has been updated yet.

The javac found in your PATH by Cooja is not capable of compiling Java 17. Either change what is in your PATH, or point Cooja to the right javac in the external tools settings.

If you are running Contiki-NG v4.8, you should use the Cooja from that release (that version of Cooja uses Java 11).

If you are running the Contiki-NG develop branch, you should use the docker image `contiker/contiki-ng` with the tag latest.

**Comment by YSmolders** [comment]
Yup that did it
Thanks for the help
