### ISSUE TITLE
cooja target should be built by cooja in border-router

### ISSUE THREAD

**Issue by aceylan** [contiki-ng/contiki-ng#2280]
Hi. 
When I want to connect router with make TARGET=cooja connect-router-cooja ;
it says cooja target should be built by cooja in new version. 
How can i solve it?
![sh](https://user-images.githubusercontent.com/4823945/202205361-25f20aed-787c-4182-92ef-0e7c653d4850.jpg)
Thank you.

**Comment by aceylan** [comment]
I tried native target too. It still waits for prefix and no connection with motes.

**Comment by pjonsson** [comment]
Does it work if you use `TARGET=zoul` instead of `TARGET=cooja`?

**Comment by pjonsson** [comment]
@aceylan Documentation has been updated, thank you for reporting the error!
