### ISSUE TITLE
Dockerize instant Contiki

### ISSUE THREAD

**Issue by simonduq** [contiki-ng/contiki-ng#23]

**Comment by g-oikonomou** [comment]
I'm suggesting this for next release.

**Comment by g-oikonomou** [comment]
Perhaps what we need is not docker, but either vagrant:
* https://www.vagrantup.com/
* https://github.com/hashicorp/vagrant

or packer:
* https://www.packer.io/
* https://github.com/hashicorp/packer

**Comment by simonduq** [comment]
Do you see any particular benefits of the two above over Docker, or just mean we should just look at all options before settling for one?

**Comment by simonduq** [comment]
Maybe also Linux Containers is an option?

**Comment by simonduq** [comment]
done https://github.com/contiki-ng/contiki-ng/pull/183
