### ISSUE TITLE
Update python-serial to python3-serial on documentation

### ISSUE THREAD

**Issue by sungminlee114** [contiki-ng/contiki-ng#2317]
Following the instruction in the [toolchain installment documentation](https://docs.contiki-ng.org/en/develop/doc/getting-started/Toolchain-installation-on-Linux.html),

`sudo apt install build-essential doxygen git git-lfs curl wireshark python-serial srecord rlwrap` 
gives an error complaining 
`Unable to locate package python-serial`.

It is due to the [change in the package name](https://github.com/edi-riga/MansOS/issues/2) of `python-serial` to `python3-serial`. Why don't we change the documentations to prevent cumbersome errors :)

**Comment by arurke** [comment]
Thanks for reporting @sungminlee114. Would you like to open a pull request with this change? ([Doc: Contributing](https://docs.contiki-ng.org/en/develop/doc/project/Contributing.html)). If not, I will do it later.

**Comment by sungminlee114** [comment]
I'm currently not available to make a pr. Could you takeover the issue? Thanks!
