### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by tlzfighting** [contiki-ng/contiki-ng#2323]
I Include the rpl.h file in the hello-world.c.

![图片](https://user-images.githubusercontent.com/95647449/206549280-23682228-3465-4df6-b6b9-aa97e9ce7783.png)

>  When I enter the compile command "make TARGET=cc2538dk build/cc2538dk/hello-world.hex", I get the following error:

hello-world.c:26:50: fatal error: os/net/ipv6/routing/rpl-lite/rpl.h: No such file or directory
compilation terminated.
make: *** [../../Makefile.include:498：build/cc2538dk/obj/hello-world.o] error .

How can Isolve this ?  Looking forward to your valuable suggestions!

**Comment by arurke** [comment]
Try skipping `ipv6/`

`#include "net/routing/rpl-lite/rpl.h"` should work fine.

**Comment by tlzfighting** [comment]
> It works . Thank you ,sir！
