### ISSUE TITLE
cc2538 debug IDE

### ISSUE THREAD

**Issue by slcmcu** [contiki-ng/contiki-ng#2363]
CC2538在调试的时候，使用什么IDE软件调试，有人知道吗?

**Comment by arurke** [comment]
Sorry, [our doc.](https://docs.contiki-ng.org/en/develop/doc/project/Where-to-report-issues%2C-ask-questions%2C-etc.html#github-issues) was not clear, but has been updated now: Issues must be in English. Please feel free to open a new issue if needed.
