### ISSUE TITLE
Constant crashing of Cooja

### ISSUE THREAD

**Issue by NestorESA** [contiki-ng/contiki-ng#2406]
I am simulating a network with one root, sometimes 2 and several nodes, it uses TSCH and RPL, most of the times whenever I pause and unpaused the simulation, cooja crashes and always the say message:
Task :run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/home/user/.gradle/jdks/adoptium-17-x64-hotspot-linux/jdk-17.0.5+8/bin/java'' finished with non-zero exit value 134

I have around 50 error report files, one from each crash, I tried finding solution online but couldn't find something useful.

**Comment by pjonsson** [comment]
I can't move tickets, but please refile this ticket in https://github.com/contiki-ng/cooja/issues

Mention whether the crash occurs inside the docker container, and what commit of Cooja that is crashing.

**Comment by NestorESA** [comment]
Hello, I did moved the ticket. Not sure about the commit.

**Comment by arurke** [comment]
Replaced by https://github.com/contiki-ng/cooja/issues/1283
