### ISSUE TITLE
Platform native fails to build with MAKE_NET_NULLNET

### ISSUE THREAD

**Issue by g-oikonomou** [contiki-ng/contiki-ng#245]
To reproduce, just open the hello-world Makefile and try to build with `MAKE_NET = MAKE_NET_NULLNET`.

I'll go as far as label it as a critical bug here guys.

**Comment by joakimeriksson** [comment]
Ok, we need to add even more compilation tests then! This should be avoided if possible - by having more variation in configs when compiling.
