### ISSUE TITLE
List: list_insert bug

### ISSUE THREAD

**Issue by simonduq** [contiki-ng/contiki-ng#254]
The function `list_insert` in `list.c` is buggy: when `previtem` is null, it pushes the new element (which (1) removes any old instance and then (2) inserts the new element). But when `previtem` is non-null, it just adds the new item without removing any old instance. Could in duplicate elements in the latter case.

Only reporting as `bug/low` because the function is currently not used in the codebase.

(report by Nikolai Kosmatov)

**Comment by g-oikonomou** [comment]
I think we need a `list_remove(list, newitem)` at the start of the else block, at line 308

**Comment by simonduq** [comment]
Yes I also think this should do

**Comment by g-oikonomou** [comment]
I'm looking at this now. The function also assumes that the caller has somehow made sure that `previtem` is already in the list.

**Comment by g-oikonomou** [comment]
For the record, things are actually worse than having the same element in the list twice: This bug will corrupt the list.

Imagine you have a list like this:

```
head --> element_1 --> element_2 --> tail
```

Now imagine you want to add the new element to the tail of the list using this function. If you call `list_insert(lst, tail, element_1);`, the function will alter `tail->next` and `element_1->next`, but will _not_ alter `head->next`. The resulting list will be:

```
head --> tail --> element_1
```
