### ISSUE TITLE
Industrial Shield's Openmote-B Board has locked up when flashing..

### ISSUE THREAD

**Issue by yoonjin2** [contiki-ng/contiki-ng#2660]
Hello, I am currently working on some projects with Openmote-B Boards.
Everytime I upload my binary into it, this only locks when trying to push it through USB Port(It does not matter when using JTag).
Flash lock, which is commonly found with wrongly programmed binary, can be my fault if that happens only in edited code, but the board also locks itself, even if I use official contiki-ng port.

p.s) Other developer guessed this problem's reason as, memory address mapping error. But I still don't get it. Hoping to get some good news soon.

Thanks, Yunjin Lee(nickname: 文堂,wentang)

**Comment by kkrentz** [comment]
Try with #1600.

**Comment by yoonjin2** [comment]
Thank you!
