### ISSUE TITLE
CoAP example will not build for Sky

### ISSUE THREAD

**Issue by iamxg** [contiki-ng/contiki-ng#273]
![image](https://user-images.githubusercontent.com/30093996/34455590-96d899ce-ed47-11e7-8d86-02634801e48c.png)

**Comment by iamxg** [comment]
Hi,
I can't resolved this issue in contiki-os 3.0. I find that there still exist this issue in this version. Who can help me!
Happy new year to everyone!
Xian Guo

**Comment by simonduq** [comment]
Thanks for reporting; we should aim for this example to compile even on Sky. Meanwhile, I encourage you to take a look at this: https://github.com/contiki-ng/contiki-ng/wiki/Tutorial:-RAM-and-ROM-usage

**Comment by g-oikonomou** [comment]
Yep, this is a bug. We can either document that it won't work, or do something to make it work.

I'm editing the title.

**Comment by iamxg** [comment]
Ok, thank you for replying.

Best Regards,

 

 

Xian G

 

 

-----Original Message-----

**Comment by g-oikonomou** [comment]
The example now documents that it is not expected to work on sky. I'm closing this.
