### ISSUE TITLE
Doxgyen online auto-upload

### ISSUE THREAD

**Issue by simonduq** [contiki-ng/contiki-ng#279]
Basically needs to be pushed at
https://github.com/contiki-ng/contiki-ng.github.io/tree/master/ngdoc

whenever a change is merged on `develop`. We could do it in Travis, using secret environment variables for the Github credentials https://docs.travis-ci.com/user/environment-variables/

**Comment by simonduq** [comment]
@nvt I believe you looked into this at some point, any more insights you want to share?

**Comment by nvt** [comment]
Yes, using Travis might be better than doing something with webhooks. I was looking at the following GitHub Gist notes, which seem to include a complete setup: https://gist.github.com/vidavidorra/548ffbcdae99d752da02#file-auto-deploy_documentation-md

**Comment by simonduq** [comment]
Let's assign this one. @nvt would you be willing/able to do this by next release?

**Comment by nvt** [comment]
@simonduq Sorry for the late reply! I had another look at the document, and I'm doubting that the access rights for maintainers are sufficient to perform all the different operations involved. It might be work smoother if a repository owner would do it.

**Comment by simonduq** [comment]
Well I think push rights to https://github.com/contiki-ng/contiki-ng.github.io is all you should need isn't it?

**Comment by simonduq** [comment]
Any update on this?

**Comment by simonduq** [comment]
Postponing to 4.2
