### ISSUE TITLE
Why not add `os/net/mac/framer` to top-level Makefile.include MODULES?

### ISSUE THREAD

**Issue by g-oikonomou** [contiki-ng/contiki-ng#298]
In the top-level `Makefile.include` we do

```Makefile
MODULES += os os/net os/net/mac os/net/routing os/storage
```

But then most platform Makefiles also do:
```Makefile
MODULES += os/net os/net/mac os/net/mac/framer
```

* Firstly, we need to remove some of that from platform Makefiles, cause it's redundant.
* Secondly, any particular reason why we are not including `os/net/mac/framer` from `Makefile.include`?

I think everything that can always compile successfully (irrespective of platform & other modules)  should be added to `MODULES` at the top-level Makefile, even if it will increase build time by a bit.

**Comment by simonduq** [comment]
Sounds good to me!
