### ISSUE TITLE
CPU_START_SOURCEFILES variable does not work with *.s assembly files

### ISSUE THREAD

**Issue by juliencombattelli** [contiki-ng/contiki-ng#302]
If the CPU_START_SOURCEFILES variable is used to store an assembly file with ".s" extension instead of ".S", the build system does not build any file (except the project source file, hello-world.c in my case).

**Comment by simonduq** [comment]
I have no strong opinion whether we should support .s, .S or both. Do you have thoughts about this? If you have a fix for `makefile.include` feel free to suggest as a PR.

**Comment by juliencombattelli** [comment]
.S files are already supported by contiki build system. You can see it lines 57, 215, and 267 of the ```makefile.include```. I think it's interesting to keep the support of assembly files, especially if it is planned to add cpu/platforms based on ARM Cortex-M, since their startup files are often written in assembly.

**Comment by simonduq** [comment]
Yes we definitely want to keep support for assembly files, the question was more on the file ext we want to support.

**Comment by juliencombattelli** [comment]
Changing all .S assembler files is a workable solution. However, it would be more convenient for developers who are porting contiki on new platforms to simply copy and paste this type of files into the source-tree without having to make any changes.

**Comment by simonduq** [comment]
Is that what you would have in mind? https://github.com/simonduq/contiki-ng/commit/038cc099f1987195191138126ae78bce70bf0c8d

**Comment by juliencombattelli** [comment]
Yes exactly, but the line with the oname variable does not seem very scalable.

**Comment by simonduq** [comment]
OK, proposed a slightly improved version at https://github.com/contiki-ng/contiki-ng/pull/321
