### ISSUE TITLE
How to run the coap example on real devices?

### ISSUE THREAD

**Issue by IvanIvan12** [contiki-ng/contiki-ng#346]
I cannot figure out how to run the coap example on real devices and get the data from real devices in Copper. Is it described somewhere how to do that? The README file contains only description for TARGET=native. I have OpenMotes.

**Comment by chenek** [comment]
For example, you can use "make TARGET=srf06-cc26xx BOARD=launchpad/cc1310 coap-example-observe-client.bin" to build coap-example-observe-client example running on TI LAUNCHXL-CC1310.

**Comment by simonduq** [comment]
We need to update the doc: https://github.com/contiki-ng/contiki-ng/issues/350

**Comment by IvanIvan12** [comment]
@chenek I tried that and it just gives me a lot of errors. But that is a client that it seems by default connects to Cooja, not to the real hardware.
