### ISSUE TITLE
Why rpl-dag-neighbor module is initialized twice?

### ISSUE THREAD

**Issue by fzy-Line** [contiki-ng/contiki-ng#349]
I read the source code of rpl-lite which is a lightweight implementation of RPL. In rpl_init function, rpl_neighbor_init function is  called once.

```
void
rpl_init(void)
{
  LOG_INFO("initializing\n");

  uip_create_linklocal_rplnodes_mcast(&rpl_multicast_addr);
  uip_ds6_maddr_add(&rpl_multicast_addr);

  rpl_dag_init();
  rpl_neighbor_init();
  rpl_timers_init();
  rpl_icmp6_init();

  rpl_ns_init();
}
```

However, in rpl_dag_init function, the rpl_neighbor_init function is called again.

```
void
rpl_dag_init(void)
{
  memset(&curr_instance, 0, sizeof(curr_instance));
  **rpl_neighbor_init();
}
```

May be it's not necessary, or may be it's right but why? Someone can help me?

**Comment by simonduq** [comment]
Good catch, this should be called only once. I would only keep the one in `rpl_init`

**Comment by simonduq** [comment]
Let me keep it open until we fix it
