### ISSUE TITLE
cc13xx platform loads bad MAC address

### ISSUE THREAD

**Issue by firmwareguru** [contiki-ng/contiki-ng#354]
The cc13xx platform (specifically observed on launchxl-cc1310 with current develop branch) starts up with a bad MAC address : ff:ff:ff:ff:ff:ff

The problem here is platform.c choosing to load a BLE MAC address because of 
#if MAKE_MAC == MAKE_MAC_BLE
and MAKE_MAC_BLE symbol is not available.

As a quick fix, replacing with this works:
#ifdef MAC_CONF_WITH_BLE

In all cases where the BLE MAC is not specified, these platforms (cc131x, cc135x) should be using the IEEE MAC from the FCFG area.

**Comment by g-oikonomou** [comment]
Thanks for the report, will look into asap

**Comment by g-oikonomou** [comment]
Confirmed. This is pretty bad.

Fix in #356, @firmwareguru could you confirm please?

**Comment by firmwareguru** [comment]
@g-oikonomou  Yes this works, thanks.
