### ISSUE TITLE
generic info

### ISSUE THREAD

**Issue by marcomilazzo** [contiki-ng/contiki-ng#391]
hi
i have some question and reading all i can ,i don't find answers!
I'm new  and i have relative confidence with contiki !
so:
i compiled the udp-server /client on cc1310 and they work perfectly
How many node i can have ? do i need to configure some defines for thousands of nodes?
or do something else? can i have more then one udp-server ?
Also i wuold like to read the rpl info from the node directly
How can i do that?
Thank's a lot for any help
Marco

**Comment by simonduq** [comment]
You'll find details of how to configure a RPL network at https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-RPL. For confirmed issues or feature requests, open a Github issue, with one single topic per issue, described with enough information to make it reproducible. For a more chat-like interaction, join our Gitter.
