### ISSUE TITLE
Pull bugfixes/PRs from contiki-os/contiki

### ISSUE THREAD

**Issue by simonduq** [contiki-ng/contiki-ng#41]
* Recently merged PRs
* Selected pending PRs

**Comment by simonduq** [comment]
Postponing this to next release, merging a core TSCH fix so close to release is too scary

**Comment by simonduq** [comment]
Hey, so we can close this one now, right?

**Comment by atiselsts** [comment]
What about keeping this open and periodically merging / encouraging to resubmit good stuff from currently open Contiki PRs?

**Comment by simonduq** [comment]
OK then shall we remove the milestone and have it long-term/running?

**Comment by g-oikonomou** [comment]
Improving stability of CC13x0 prop-mode, as discussed in contiki-os/contiki#2161

**Comment by joakimeriksson** [comment]
Maybe this can be closed by now? It feels like Contiki OS is no longer getting too many PR:s

**Comment by atiselsts** [comment]
Agree.
