### ISSUE TITLE
differences between Contiki and Contiki-ng

### ISSUE THREAD

**Issue by marcomilazzo** [contiki-ng/contiki-ng#413]
hi
i have one udp-server and 10 udp-clients  with cc1310
i compiled Contiki with non storing 
#define WITH_NON_STORING 1 /* Set this to run with non-storing mode */
allo runs fine . the only differance is that to call the client  i must use fd80 while receiving fd00 
but i woorks

i compiled contiki-ng  with udp-client server  and  the 10 node clients will reset !!!
every 50 connections like
Also compiled the contiki code in the contiki-ng  with classic RPL 
In this case i can transmitt to clients but don't receive anything
Can somebody please help me
i'm i missing something ?
Contiki-ng is supposed to work in lite rpl and non storing mode !!
Any suggestions?
I really love contigi-ng and i would like to use only this
Ciao
marco

**Comment by simonduq** [comment]
Same comment as #391 applies here.
