### ISSUE TITLE
CoAP documentation and tutorials

### ISSUE THREAD

**Issue by simonduq** [contiki-ng/contiki-ng#420]
The CoAP documentation page mentions more doc to come after #16 and #42 is merged... which is now the case :) Also, we're still lacking a CoAP tutorial.

I'm happy to take care of creating the tutorial.
@nfi @joakimeriksson for the doc?

**Comment by zhitaoh** [comment]
The current examples/coap dir contains an example client that uses the blocking API. Ideally there should be a separate example that showcases the usage of the alternative non-blocking, "callback" API.

It would be good to have another example to show how to switch on transport layer encryption using the coap_endpoint_connect()/disconnect() functions.

**Comment by simonduq** [comment]
Tutorial available at: https://github.com/contiki-ng/contiki-ng/wiki/Tutorial:-CoAP

**Comment by simonduq** [comment]
And documentation at https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-CoAP
