### ISSUE TITLE
pwm duty cycle

### ISSUE THREAD

**Issue by marcomilazzo** [contiki-ng/contiki-ng#424]
hi
does anybody nows how to set the PWM duty cycle for cc2650 cc1319
The buzzer.c (controlled by pwm) used in the mqtt-web-demo sets the frequency 
works fine
but i can't understand how i set duty cycle
thank's
marco

**Comment by simonduq** [comment]
Please read this: https://github.com/contiki-ng/contiki-ng/wiki/Where-to-report-issues,-ask-questions,-etc.%3F
