### ISSUE TITLE
how to add device to blacklist and to refresh netkey 

### ISSUE THREAD

**Issue by amigomcu** [contiki-ng/contiki-ng#441]
hi all,
how to leave a node at network ?

That node  i need to Remove from network. 
i think it should be alike network , 
add the node in blacklist and refresh network key with others.

how to add device to blacklist and to refresh netkey ?

**Comment by simonduq** [comment]
Please read this: https://github.com/contiki-ng/contiki-ng/wiki/Where-to-report-issues,-ask-questions,-etc.%3F
