### ISSUE TITLE
Test out-of-tree builds on travis

### ISSUE THREAD

**Issue by g-oikonomou** [contiki-ng/contiki-ng#482]
Building from outside the tree has been something that we have always kinda wanted and half-supported. I think we should make a more conscious effort to support it. This may (or may not) involve bug fixing (I am thinking #432 here) and it would also be nice to test such out-of-tree builds on travis.

**Comment by simonduq** [comment]
I'm guessing this is more a long-term thing than 4.2, or?

**Comment by g-oikonomou** [comment]
I just created a hello-world dir out of tree and I can build for native, zoul, srf06-cc26xx

**Comment by simonduq** [comment]
Closed with https://github.com/contiki-ng/contiki-ng/pull/717
