### ISSUE TITLE
How enable/use LLSEC to test rpl-border-router and cc26xx-web-demo running on LAUNCHXL-CC1310?

### ISSUE THREAD

**Issue by chenek** [contiki-ng/contiki-ng#496]
I would like to enable/use LLSEC to test cc26xx-web-demo running on LAUNCHXL-CC1310 to communicate with rpl-border-router running on Raspberry Pi with LAUNCHXL-CC1310 as slip-radio. However, I cannot find any explicit document showing me how to do it. Does anyone make this work before? or LAUNCHXL-CC1310 cannot support LLSEC?

**Comment by simonduq** [comment]
Hey wait, just wanted to clarify one thing: link-layer security is supported in TSCH (see TSCH doc and tutorials), but missing in CSMA. There is no longer a layer called `LLSEC`, but that does not mean there is no link-layer security. But of course with cc1310 the issue is we don't have TSCH.

**Comment by chenek** [comment]
@simonduq so, will Contiki-NG support TSCH on CC13xx?

**Comment by simonduq** [comment]
Yes that's absolutely on the roadmap. And part of https://github.com/contiki-ng/contiki-ng/issues/21

**Comment by chenek** [comment]
Thanks @simonduq
