### ISSUE TITLE
Update Docker image to latest compilers

### ISSUE THREAD

**Issue by simonduq** [contiki-ng/contiki-ng#517]
And make sure to remove `-Wno-unused-const-variable` from `Makefile.include` once this is done. See https://github.com/contiki-ng/contiki-ng/issues/514

**Comment by simonduq** [comment]
Depends on https://github.com/contiki-ng/contiki-ng/issues/678

**Comment by simonduq** [comment]
Postponing to 4.3

**Comment by joakimeriksson** [comment]
Docker and compilers are updated.
