### ISSUE TITLE
is this project sync with origin github/contiki-os?

### ISSUE THREAD

**Issue by alexrayne** [contiki-ng/contiki-ng#524]
i`ve look to history, and see that github/contiki-os master on sync with this one project.
do you plan to merge with contiki-os?

**Comment by yatch** [comment]
I don't think so. 

Regarding the history you looked, contiki-ng started as a fork of contiki-os as as [this document](https://github.com/contiki-ng/contiki-ng/wiki/More-about-Contiki‐NG) says. That's why you see commits of contiki-os in contiki-ng commit history.

**Comment by simonduq** [comment]
Let me also point you to this: https://github.com/contiki-ng/contiki-ng/wiki/Where-to-report-issues,-ask-questions,-etc.%3F
