### ISSUE TITLE
Ext-flash SensorTag cc2650

### ISSUE THREAD

**Issue by AntonioLangiu** [contiki-ng/contiki-ng#530]
I'm trying to use the external flash with the SensorTag cc2650. After several tries I compiled the `cc26xxx-web-demo` example and I noticed that the new interface to interact with the SPI flash is failing also there:

```
[INFO: Main      ] Starting Contiki-NG-release/v4.1-138-g458178513-dirty
[INFO: Main      ] - Routing: RPL Lite
[INFO: Main      ] - Net: sicslowpan
[INFO: Main      ] - MAC: CSMA
[INFO: Main      ] - 802.15.4 PANID: 0xabcd
[INFO: Main      ] - 802.15.4 Default channel: 26
[INFO: Main      ] Link-layer address 0012.4b00.0afe.bd04
[INFO: Main      ] Tentative link-local IPv6 address fe80::212:4b00:afe:bd04
[INFO: CC26xx/CC13xx] TI CC2650 SensorTag
[INFO: CC26xx/CC13xx]  RF: Channel 26, PANID 0xABCD
[INFO: CC26xx/CC13xx]  Node ID: 48388
CC26XX Web Demo Process
CC26XX Web Server
CC26XX CoAP Server
CC26XX Net UART Process
Could not open flash to load config
```

After some debugging I noticed that the failure is happening [here](https://github.com/contiki-ng/contiki-ng/blob/develop/arch/dev/ext-flash/ext-flash.c#L223).

Is there something I'm doing wrong?

**Comment by g-oikonomou** [comment]
How are you getting the tag to print debug output for you?

**Comment by g-oikonomou** [comment]
I'm also curious as to the values of `rbuf[0]` and `rbuf[1]`. Can you add a print for them in the fail scenario, just before the `return VERIFY_PART_POWERED_DOWN;`?

**Comment by chenek** [comment]
The CC2650 on the SensorTag uses the same I/O pin for SPI SCLK signal and JTAG TDI signal. The current firmware version of the XDS110 does not support the 2-pin c-JTAG standard, so it needs to use TDI and TDO in addition to TCK and TMS (full 4-pin JTAG). Due to this shared resource, it is not possible to access the external serial flash while debugging the SensorTag with the Debug DevPack. You can refer to http://processors.wiki.ti.com/index.php/Debug_DevPack_User_Guide

**Comment by AntonioLangiu** [comment]
@g-oikonomou I'm using the Debug DevPack. The values of `rbuf[0]` and `rbuf[1]` are `0xEF` and `0x12` respectively.

**Comment by g-oikonomou** [comment]
OK so what @chenek is the primary suspect here.

I'd also like to double-check that the DID and MID defined in [`board.h`](https://github.com/contiki-ng/contiki-ng/blob/develop/arch/platform/srf06-cc26xx/sensortag/cc2650/board.h) are correct for your device. We did test them, but I believe there have been older sensortags using a different flash part, so could yours be one of them?

```
#define EXT_FLASH_DEVICE_ID         0x14
#define EXT_FLASH_MID               0xC2
```

**Comment by AntonioLangiu** [comment]
Yep! I think this is the problem! I fixed it with this patch:
```
 --- a/arch/platform/srf06-cc26xx/sensortag/cc2650/board.h
 +++ b/arch/platform/srf06-cc26xx/sensortag/cc2650/board.h
 @@ -149,8 +149,8 @@
  #define EXT_FLASH_SPI_PIN_MISO      18
  #define EXT_FLASH_SPI_PIN_CS        14

 -#define EXT_FLASH_DEVICE_ID         0x14
 -#define EXT_FLASH_MID               0xC2
 +#define EXT_FLASH_DEVICE_ID         0x12
 +#define EXT_FLASH_MID               0xEF

  #define EXT_FLASH_PROGRAM_PAGE_SIZE 256
  #define EXT_FLASH_ERASE_SECTOR_SIZE 4096
 --
 2.13.1
```

**Comment by g-oikonomou** [comment]
Ah we cross posted there... Please change board.h with those values. Looks like your device is wearing a Winbond... Just out of curiosity, how old is your tag? Does it have a revision sticker on it?

**Comment by g-oikonomou** [comment]
It's a W25X40CL (4Mbit).

**Comment by AntonioLangiu** [comment]
Yes, it has a revision sticker on it and says `Rev: 1.3.0` and `HW Rev 1.2.0`. (I don't know how old is it since I did not directly buy it, but I'll ask).

**Comment by g-oikonomou** [comment]
It's an older one. New ones have the MX25R8035F (8MBit).

What a mess... I need to think about this.

**Comment by g-oikonomou** [comment]
@AntonioLangiu please try #534 

Simply defining `SENSORTAG_CC2650_REV_1_2_0` as 1 in your `contiki-conf.h` or `project-conf.h` should do it for you.

**Comment by AntonioLangiu** [comment]
I tested it with the `cc26xxx-web-demo` example and I confirm that it fixes the problem.
