### ISSUE TITLE
Add support for TI cc13x2 and cc26x2 platforms

### ISSUE THREAD

**Issue by firmwareguru** [contiki-ng/contiki-ng#564]
This issue is to track the progress of the various porting efforts in the Contiki ecosystem to support the TI cc13x2 and cc26x2 devices.  These platforms should be ported into Contiki and Contiki-NG at the same time.

Porting efforts known at this time:

- https://github.com/firmwaremodules/contiki/tree/cc26x2-cc13x2
The goal of this porting effort is to investigate and implement maximum code re-use across all cc13xx and cc26xx device families.
- https://github.com/necropaz/contiki-ng/tree/develop

Relevant Contiki-NG issues:
- #83

**Comment by firmwareguru** [comment]
I'm looking at this in the context of Contiki first.  I've started a [wiki ](https://github.com/firmwaremodules/contiki/wiki/Texas-Instruments-CC26X2-CC13X2-Contiki-Port )to document what is happening.

**Comment by simonduq** [comment]
That's awesome :)

**Comment by MartinNPN** [comment]
Hello,

ti is even working on a port, maybe this would be the cleanest way. I think that they will open a PR before October.

**Comment by firmwareguru** [comment]
Alright, looks like it's done!  See PR #609.  I'm closing this.
