### ISSUE TITLE
Add LWM2M with Queue Mode Tutorial in the Wiki

### ISSUE THREAD

**Issue by carlosgp143** [contiki-ng/contiki-ng#576]
Hi!

I have created this [Queue Mode tutorial](https://github.com/contiki-ng/wiki-sandbox/wiki/Tutorial:-LWM2M-and-IPSO-Objects-with-Queue-Mode) in the Wiki sandbox. It teaches the user on how to enable Queue Mode for the example-ipso-objects, download a Leshan Server that supports Queue Mode and run everything together.

It would be nice to add it at the end of the [LWM2M Tutorial](https://github.com/contiki-ng/contiki-ng/wiki/Tutorial:-LWM2M-and-IPSO-Objects) or in a separate page, that's up to you :-) (in case of a separate page I need to change some parts, as they reference to "the beginning of the tutorial")

**Comment by simonduq** [comment]
Done, thanks a lot!! :)

**Comment by carlosgp143** [comment]
Thanks! It would be nice to change this sentence as it is a new page in the wiki:

After doing all this, the example-ipso-objects.c can be compiled and programmed into the device as it was explained "at the beginning of this tutorial". 

Instead of "at the beginning of this tutorial", have a link to the LWM2M tutorial :-)

**Comment by simonduq** [comment]
Done, txs
