### ISSUE TITLE
Small fix in the LWM2M with Queue Mode Tutorial

### ISSUE THREAD

**Issue by carlosgp143** [contiki-ng/contiki-ng#582]
Hi! 

I just realized that I missed one important aspect in the LWM2M with Queue Mode tutorial, which is to define the sleep and wake up behavior according to the hardware platform through the `module-macros.h`. So I have created [this page](https://github.com/contiki-ng/wiki-sandbox/wiki/LWM2M-and-IPSO-Objects-with-Queue-Mode) in the sandbox, which has the same content as before plus the new stuff. 

Can someone substitute the old tutorial with this new page? :-) And sorry for forgetting that important part...

**Comment by simonduq** [comment]
Done. Thanks!
