### ISSUE TITLE
Homogenize platforms

### ISSUE THREAD

**Issue by simonduq** [contiki-ng/contiki-ng#6]
Avoid code duplication.

Common main (George: Perhaps one that allows platform-specific hooks)

Common examples (now we have the same examples copied 10 times). George: See what I’ve done with sensniff in order to be able to provide a more-or-less-but-not-quite platform independent example. Design could perhaps be improved, but we should be able to have BRs and Slip Radios using similar design.

**Comment by g-oikonomou** [comment]
This is a combination of:

* [x] #86
* [ ] #99 
* [ ] #122
* [ ] #123
* [ ] #131
* [ ] #132
* [ ] #133

Once those are merged, I am closing this as achieved.

**Comment by simonduq** [comment]
This is done!
