### ISSUE TITLE
TSCH backup link

### ISSUE THREAD

**Issue by seungbumz** [contiki-ng/contiki-ng#625]
Hi. I am studying TSCH protocol.

In TSCH, backup link is used when there is no packet to send in current link.

And the comment in the code says "Backup link must have Rx flag".

It means, the link with Tx flag only (without Rx flag) is not available for backup link.

Why??

**Comment by seungbumz** [comment]
Thanks for your reply.

It will be very helpful to my work.

2018년 8월 22일 (수) 오후 4:21, Simon Duquennoy <notifications@github.com>님이 작성:

**Comment by firmwareguru** [comment]
@seungbumz Can we close this issue then?
