### ISSUE TITLE
multiple definition of `ecc_ecdsa_sign' when targeting srf06-cc26xx with dtls

### ISSUE THREAD

**Issue by tdesmet** [contiki-ng/contiki-ng#628]
If you build the coap-example-client for the cc1310 launchpad with DTLS you get the following error:
`make TARGET=srf06-cc26xx BOARD=launchpad/cc1310 MAKE_WITH_DTLS=1`
```
obj_srf06-cc26xx/ecc.o: In function `ecc_ecdsa_sign':
ecc.c:(.text.ecc_ecdsa_sign+0x0): multiple definition of `ecc_ecdsa_sign'
obj_srf06-cc26xx/rom_crypto.o:(.data.ecc_ecdsa_sign+0x0): first defined here
collect2: error: ld returned 1 exit status
```

**Comment by g-oikonomou** [comment]
Yep, seen that one mentioned before. Clearly we need to do something about this, either rename one or the other...

**Comment by tdesmet** [comment]
any preference on which one to rename and what the new name should be?

**Comment by g-oikonomou** [comment]
Selfishly, I'd rename the one that ships with DTLS :)

**Comment by tdesmet** [comment]
I think this issue can be closed?
