### ISSUE TITLE
Flash/Connection issue with nrf52dk

### ISSUE THREAD

**Issue by npcode15** [contiki-ng/contiki-ng#662]
Hello, I am having trouble flashing the board nrf52dk.

**Setup**: Windows 10 Host, Virtual Contiki OS (Ubuntu 14). Using VMWare Workstation Player.
**Contiki Version**: InstantContiki3.0

I am following the Tutorials from these links: 

1) https://devzone.nordicsemi.com/b/blog/posts/setting-up-ipv6-over-ble-using-nrf52-series-and-co
2) https://github.com/contiki-ng/contiki-ng/wiki/Platform-nrf52dk

**Command**: Target=nrf52dk make
![image](https://user-images.githubusercontent.com/25517038/45601021-ab67b400-b9cb-11e8-922a-ea2d7f8ecc9a.png)

I am able to connect with the device using J-Link using both connect and USB.
So, Contiki-OS is able to read and connect with the device correctly. 

I think the platform nrf52dk is missing. I can see it is present on GitHub but missing in the vmsd image.
Please refer to 2 images below for reference.
![image](https://user-images.githubusercontent.com/25517038/45601639-fab2e200-b9d5-11e8-8881-019c75993298.png)
![image](https://user-images.githubusercontent.com/25517038/45601660-482f4f00-b9d6-11e8-9e35-12dac002eddd.png)

Please help, Thank you.

**Comment by g-oikonomou** [comment]
We do not support instant-contiki (although it should be no problem to download and use Contiki-NG into an instant-contiki VM). Depending on your setup, suggest using either docker or vagrant - see the respective wiki guides for information on which to choose and how to deply.

I'll close this, feel free to join us on gitter.

**Comment by npcode15** [comment]
Thank you.
