### ISSUE TITLE
fixed two code paths in Wiki page

### ISSUE THREAD

**Issue by zhitaoh** [contiki-ng/contiki-ng#675]
[The current Wiki page on TSCH and 6TiSCH](https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-TSCH-and-6TiSCH)  includes:
os/net/mac/frame802154.[ch]: handling of frame version 2
os/net/mac/frame802154-ie.[ch]: handling of Information Elements

They should be:
os/net/mac/framer/frame802154.[ch]: handling of frame version 2
os/net/mac/framer/frame802154-ie.[ch]: handling of Information Elements

[Wiki page with proposed change](https://github.com/contiki-ng/wiki-sandbox/wiki/Documentation:-TSCH-and-6TiSCH)

**Comment by simonduq** [comment]
Thanks Zhitao, fixed!
