### ISSUE TITLE
RPL wiki page typos

### ISSUE THREAD

**Issue by zhitaoh** [contiki-ng/contiki-ng#677]
[The RPL Wiki page](https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-RPL) contains some typos. Here are proposed fixes.

any node to a toward a root
=>
any node to a root

For storing node
=>
For storing mode

Whenever heading a DIO
=>
Whenever hearing a DIO

the node might chose to
=>
the node might choose to

at the expanse of
=>
at the expense of

Once a preferred parent is chosen will then register itself through a DAO
=>
Once a preferred parent is chosen, a node will then register itself through a DAO

Nodes will resent a DAO
=>
Nodes will resend a DAO

it will effectively leave the DAG
=>
it will eventually leave the DAG

**Comment by simonduq** [comment]
Fixed, thanks a lot!
