### ISSUE TITLE
How to keep CC2650 deep-sleeping for as long as possible?

### ISSUE THREAD

**Issue by wumin1** [contiki-ng/contiki-ng#690]
Hi all,

I'm trying to implement an application where cc2650 mote needs to sleep for rather long period (hours). However, I found it regularly woke with RPL (@1Hz) and uip_ds6_periodic (@UIP_DS6_CONF_PERIOD) duties from tcpip process.  I can switch off RPL since I don't need routing feature on the mote. Is it possible to set UIP_DS6_CONF_PERIOD a large number rather than default value (1/10s) or 1s as suggested in the example?

Also I wonder, if it is possible to pause tcpip process during deep sleep?

**Comment by g-oikonomou** [comment]
I'd say it's a bad idea to stop the TCP/IP process while sleeping, it needs to do some housekeeping of data structures among other things. I am afraid we don't have an off-the-shelf easy way to deep sleep for e.g. minutes at the moment.

I'll close this. Welcome to join us on gitter!
