### ISSUE TITLE
RPL Wiki Page Broken Link

### ISSUE THREAD

**Issue by edrose** [contiki-ng/contiki-ng#710]
There is a broken link in the Wiki on [the page about RPL](https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-RPL). 

Under the header "RPL Lite: topology formation and configuration" the link points to a header file on the master branch in `os/net/rpl-lite`, but it appears to have changed into the `os/net/routing/rpl-lite` folder . I believe the new link should be https://github.com/contiki-ng/contiki-ng/blob/master/os/net/routing/rpl-lite/rpl-conf.h which reflects this new folder location.

**Comment by yatch** [comment]
Thank you! I've fixed the link:

https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-RPL#rpl-lite-topology-formation-and-configuration
