### ISSUE TITLE
tsch: re-synchronization can interfere with time source selection by RPL

### ISSUE THREAD

**Issue by debug-ito** [contiki-ng/contiki-ng#712]
In `keepalive_packet_sent` in `tsch.c`, the node tries to re-synchronize with `last_eb_nbr_addr` if it fails to receive ACK for the keepalive frame. This can overwrite the time source selected by RPL and set in `tsch_rpl_callback_parent_switch`. As a result, the time source becomes inconsistent with RPL preferred parent.

How can we avoid this problem? I suggest comparing the current time source (obtained by `tsch_queue_get_time_source`) with the KA target (obtained by `packetbuf_addr(PACKETBUF_ADDR_RECEIVER)`). If they are different addresses, it implies someone has already changed the time source, so we don't have to change it anymore.

**Comment by debug-ito** [comment]
I think the problem occurs in the first case, that is, RPL switched parent between the time where we issued the last KA and the time we get the NOACK callback.

In the second case, I think the out-of-sync state is only temporary. RPL will change the time source anyway.

**Comment by debug-ito** [comment]
OK, I'll submit a PR later.

**Comment by simonduq** [comment]
Thanks!
