### ISSUE TITLE
Toolchain installation instructions in wiki page

### ISSUE THREAD

**Issue by khongyew** [contiki-ng/contiki-ng#728]
In the wiki [page](https://github.com/contiki-ng/contiki-ng/wiki/Toolchain-installation-on-Linux)
The instruction to install the ARM toolchain is currently as follow:
`$ sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa `
`$ sudo apt update`
`$ sudo apt install srecord gcc-arm-embedded`
This installs version 7 of the toolchain, which failed to compile cc26xx-web-demo using `make TARGET=srf06-cc26xx BOARD=sensortag/cc2650 `

Version 5 of the toolchain works.
instruction for version 5 installation can be found at: [https://github.com/contiki-ng/contiki-ng/blob/develop/tools/vagrant/bootstrap.sh](url)

**Comment by atiselsts** [comment]
I agree that relying on `apt install` can give bad results. We've also seen a problem (discovered by an unlucky student) with a version of `arm-gcc` that can successfully build executables, but they do not work when flashed to the node.

**Comment by g-oikonomou** [comment]
Yeah these instructions are bad. I'll update all relevant pages, thanks for reporting this.

That's my recommended page to download from: https://developer.arm.com/open-source/gnu-toolchain/gnu-rm

**Comment by khongyew** [comment]
Do you guys also use arm-gcc version 5?

**Comment by g-oikonomou** [comment]
I have multiple versions installed in parallel and I switch among them. I've recently been using 5.2, but I also tried without problems last week with latest.

**Comment by g-oikonomou** [comment]
I've updated all relevant wiki pages. Thanks for raising this, I'll close this (hopefully not just "for now" :))
