### ISSUE TITLE
tunslip6 does not work on default Ubuntu18.04

### ISSUE THREAD

**Issue by tsakoda** [contiki-ng/contiki-ng#741]
I tried to connect Contiki-NG on CC1310 with tunslip6 module. However, tunslip6 does not work and prints error message "ifconfig: not found" and "netstat: not found" because I use Ubuntu 18.04 and net-tools is not installed in default ubuntu 18.04.

Please write the tunslip documents that tunslip6 needs the net-tools and install it.

**Comment by g-oikonomou** [comment]
Thanks, I've done that.
