### ISSUE TITLE
 A pass on all documentation pages prior to 4.2

### ISSUE THREAD

**Issue by g-oikonomou** [contiki-ng/contiki-ng#742]
For general documentation: **please make a pass, update what needs to be including config flags, log output etc.** 
For tutorials: **please run, fix accordingly, update log output**

# Documentation

## Setting up Contiki-NG

* [x] [Docker image](https://github.com/contiki-ng/contiki-ng/wiki/Docker)
* [x] [Vagrant image](https://github.com/contiki-ng/contiki-ng/wiki/Vagrant)
* [x] [Native toolchain installation (Linux)](https://github.com/contiki-ng/contiki-ng/wiki/Toolchain-installation-on-Linux)
* [x] [Native toolchain installation (OS X)](https://github.com/contiki-ng/contiki-ng/wiki/Toolchain-installation-on-OS-X)
* [x] [IP64 setup with Jool](https://github.com/contiki-ng/contiki-ng/wiki/NAT64-for-Contiki%E2%80%90NG)
* [x] [The Contiki-NG build system](https://github.com/contiki-ng/contiki-ng/wiki/The-Contiki%E2%80%90NG-build-system)
* [x] [The Contiki-NG configuration system](https://github.com/contiki-ng/contiki-ng/wiki/The-Contiki%E2%80%90NG-configuration-system)
* [x] [The Contiki-NG logging system](https://github.com/contiki-ng/contiki-ng/wiki/The-Contiki%E2%80%90NG-logging-system)

## Programming Contiki-NG

* [x] [Repository structure](https://github.com/contiki-ng/contiki-ng/wiki/Repository-structure)
* [x] [Processes and events](https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-Processes-and-events)
* [x] [Timers](https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-Timers)
* [x] [Memory management](https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-Memory-management)
* [x] [Packet buffers](https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-Packet-buffers)
* [x] [Energy monitoring with Energest](https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-Energest)
* [x] [UDP communication](https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-UDP-communication)
* [x] [IPv6-less networking with NullNet](https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-NullNet)
* [x] [A guide on porting Contiki-NG to new platforms](https://github.com/contiki-ng/contiki-ng/wiki/Porting-Contiki%E2%80%90NG-to-new-platforms)
* [x] We also provide API documentation, albeit partial, via [Doxygen](https://contiki-ng.github.io/ngdoc/modules)

## Key networking modules and services

* [x] [IPv6 networking stack](https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-IPv6)
* [x] [IPv6 multicast](https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-IPv6-multicast)
* [x] [The RPL routing protocol](https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-RPL)
* [x] [CoAP and CoAPs](https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-CoAP)
* [x] [OMA LWM2M](https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-LWM2M)
* [x] [TSCH and 6TiSCH](https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-TSCH-and-6TiSCH)
* [x] [6TiSCH 6top sublayer](https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-6TiSCH-6top-sub-layer)
* [x] [6TiSCH scheduler Orchestra](https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-Orchestra)
* [x] [MQTT](https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-MQTT)

## Storage systems
* [x] [Coffee File System](https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-Coffee)
* [x] [Antelope database management system](https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-Antelope)

## The Contiki-NG platforms

* [x] [cc2538dk: TI cc2538 development kit](https://github.com/contiki-ng/contiki-ng/wiki/Platform-cc2538dk)
* [x] [cooja: Cooja native motes platform](https://github.com/contiki-ng/contiki-ng/wiki/Platform-cooja)
* [x] [jn516x: NXP jn516x series](https://github.com/contiki-ng/contiki-ng/wiki/Platform-jn516x)
* [x] [native: Contiki-NG as a native process](https://github.com/contiki-ng/contiki-ng/wiki/Platform-native)
* [x] [nrf52dk: Nordic Semiconductor nRF52 development kit](https://github.com/contiki-ng/contiki-ng/wiki/Platform-nrf52dk)
* [x] [openmote-cc2538: OpenMote cc2538](https://github.com/contiki-ng/contiki-ng/wiki/Platform-openmote-cc2538)
* [x] [simplelink: TI SimpleLink MCU Platform](https://github.com/contiki-ng/contiki-ng/wiki/Platform-simplelink)
* [x] [sky: Tmote Sky / TelosB](https://github.com/contiki-ng/contiki-ng/wiki/Platform-sky)
* [x] [srf06-cc26xx: TI cc26xx and cc13xx platforms](https://github.com/contiki-ng/contiki-ng/wiki/Platform-srf06-cc26xx)
* [x] [zoul: Zolertia Zoul platforms: Firefly, RE-mote and Orion](https://github.com/contiki-ng/contiki-ng/wiki/Platform-zoul)

# Tutorials

Basics:
* [x] [Hello, World!](https://github.com/contiki-ng/contiki-ng/wiki/Tutorial:-Hello,-World!)
* [x] [Logging](https://github.com/contiki-ng/contiki-ng/wiki/Tutorial:-Logging)
* [x] [NG shell](https://github.com/contiki-ng/contiki-ng/wiki/Tutorial:-Shell)
* [x] [RAM and ROM usage](https://github.com/contiki-ng/contiki-ng/wiki/Tutorial:-RAM-and-ROM-usage)
* [x] [Energy monitoring](https://github.com/contiki-ng/contiki-ng/wiki/Tutorial:-Energy-monitoring)
* [x] [Timers and events](https://github.com/contiki-ng/contiki-ng/wiki/Tutorial:-Timers-and-events)

Networking:
* [x] [IPv6 ping](https://github.com/contiki-ng/contiki-ng/wiki/Tutorial:-IPv6-ping)
* [x] [RPL basics](https://github.com/contiki-ng/contiki-ng/wiki/Tutorial:-RPL)
* [x] [RPL with border router](https://github.com/contiki-ng/contiki-ng/wiki/Tutorial:-RPL-border-router)
* [x] [TSCH and 6TiSCH](https://github.com/contiki-ng/contiki-ng/wiki/Tutorial:-TSCH-and-6TiSCH)
* [x] [CoAP](https://github.com/contiki-ng/contiki-ng/wiki/Tutorial:-CoAP)
* [x] [LWM2M](https://github.com/contiki-ng/contiki-ng/wiki/Tutorial:-LWM2M-and-IPSO-Objects)
* [x] [MQTT](https://github.com/contiki-ng/contiki-ng/wiki/Tutorial:-MQTT)

Simulation:
* [x] [Cooja: getting started](https://github.com/contiki-ng/contiki-ng/wiki/Tutorial:-Running-Contiki%E2%80%90NG-in-Cooja)
* [x] [Cooja: simulating a RPL network](https://github.com/contiki-ng/contiki-ng/wiki/Tutorial:-running-a-RPL-network-in-Cooja)
* [x] [Cooja: simulating a RPL network with a border router](https://github.com/contiki-ng/contiki-ng/wiki/Cooja:-simulating-a-border-router)
* [x] [Running Contiki-NG in Renode](https://github.com/contiki-ng/contiki-ng/wiki/Tutorial:-Running-Contiki%E2%80%90NG-in-Renode)

# Organization, etc.

* [x] [Organization](https://github.com/contiki-ng/contiki-ng/wiki/Organization)
* [x] [Contributing](https://github.com/contiki-ng/contiki-ng/wiki/Contributing)
* [x] [Code style](https://github.com/contiki-ng/contiki-ng/wiki/Code-style)
* [x] [Development cycle](https://github.com/contiki-ng/contiki-ng/wiki/Development-cycle)
* [x] [Releases](https://github.com/contiki-ng/contiki-ng/wiki/Releases)
* [x] [Roadmap](https://github.com/contiki-ng/contiki-ng/wiki/Roadmap)
* [x] [Issue and PR labels](https://github.com/contiki-ng/contiki-ng/wiki/Issue-and-Pull-Request-Labels)
* [x] [Where to report issues, ask questions, etc.?](https://github.com/contiki-ng/contiki-ng/wiki/Where-to-report-issues,-ask-questions,-etc.%3F)

[doc:more-about-contiki-ng]: https://github.com/contiki-ng/contiki-ng/wiki/More-about-Contiki%E2%80%90NG

**Comment by simonduq** [comment]
Done :)
