### ISSUE TITLE
[wiki] native toolchain on OS X update

### ISSUE THREAD

**Issue by JelmerT** [contiki-ng/contiki-ng#744]
https://github.com/contiki-ng/wiki-sandbox/wiki/Toolchain-installation-on-macOS

Changes:
-Added python as a dependency to be installed with brew. AFAIK pip isn't installed with the pyhton coming with macOS. So to make sure people don't get stuck at the next step, just install python3 (which installs pip)

-Also changed OS X naming to new macOS naming in title.

(Why can't I create a pull request for the wiki, github? :octocat: ?)

**Comment by g-oikonomou** [comment]
👍
