### ISSUE TITLE
Simplelink cc13x2 and cc26x2 target .bin files too big

### ISSUE THREAD

**Issue by firmwareguru** [contiki-ng/contiki-ng#756]
Builds for the simplelink cc13x2 and cc26x2 targets generate .bin files that are way too big (524 MB in fact).  This is because of the way the DMA data structures are placed in the linker file.

This applies to all simplelink targets including cc13x0-cc26x0.  Observed building the `examples/hello-world` project.

**Comment by firmwareguru** [comment]
@tiepettersen   FYI

**Comment by tiepettersen** [comment]
@firmwareguru, thanks for fixing this. Will take a look next week to verify there aren't any similar issues.
