### ISSUE TITLE
How I can manage IoT nodes ?

### ISSUE THREAD

**Issue by EngKhaled91** [contiki-ng/contiki-ng#762]
Hello,
I want to see if possible to manage IoT nodes using protocols like (CoAP, SNMP, NETCONF, ..)
are there any tutorials or examples for  this ?
thanks for your supporting 
Khaled

**Comment by firmwareguru** [comment]
It is certainly possible.  A popular way to do this in real-time would be through LWM2M/IPSO-objects (built on CoAP).  There is an [example](https://github.com/contiki-ng/contiki-ng/tree/develop/examples/lwm2m-ipso-objects) and a [wiki](https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-LWM2M) to support it.  

Other ways include using MQTT by subscribing to topics with configuration / control info.  The nodes can wake up according to their schedule and poll the topics.  This has higher latency but is suitable for many applications.

You could even make an HTTP GET request to a web server to grab arbitrary management data like a JSON structure or something even simpler.
