### ISSUE TITLE
strings.h: No such file or directory

### ISSUE THREAD

**Issue by Rockabilly15** [contiki-ng/contiki-ng#766]
I tried to make and upload mqtt-client to sky mote, but as issue #696 suggest this is excluded. I just change the command to make mqtt-client.sky TARGET=sky and I got the above response. So my problem is whether there's a way to run mqtt-client on my sky mote? Thanks.

**Comment by g-oikonomou** [comment]
I am afraid the Sky platform is too limited for this example, so not supporting it is intentional.
