### ISSUE TITLE
Simplelink platform opt3001 sensor returning wrong lux value

### ISSUE THREAD

**Issue by firmwareguru** [contiki-ng/contiki-ng#768]
@tiepettersen This one is for you.

I'm setting up my own platform using this sensor and in the process found the bug in

https://github.com/contiki-ng/contiki-ng/blob/develop/arch/platform/simplelink/cc13xx-cc26xx/sensortag/opt-3001-sensor.c

In function value(), conversion of result to lux (or cenitlux) should be:

```
  uint32_t m = (result_value & 0x0FFF) >> 0;
  uint32_t e = (result_value & 0xF000) >> 12;
  uint32_t converted = m * 1 * (1 << e);
```
The m and e got mixed up and the factor 100 is applied to scale the formula's 0.01 to a 1.

**Comment by g-oikonomou** [comment]
#821
