### ISSUE TITLE
jn516x: check_rtimer_overflow issue

### ISSUE THREAD

**Issue by pjenish94** [contiki-ng/contiki-ng#780]
the timer shows overflow even when the value is not actually overflowed.
i am currently using jn5168 and i have view that the value if last_rtimer_ticks is greater than now before the actual over flow value which is 4294967295. But my overflow occurs at last_rtimer_ticks =1207797178 where as now value is 1207797120. according to the code last_rtimer_ticks is updated by now value so how does last_rtimer_ticks value exceed more than now.

**Comment by nvt** [comment]
This platform was removed recently, so I'm closing the issue.
