### ISSUE TITLE
Enable the VirtualBox GUI using the Vagrant image

### ISSUE THREAD

**Issue by h-hosseini** [contiki-ng/contiki-ng#781]
After installing Contiki-ng by using the Vagrant image, we ( @ElisaRojas ) wanted to activate GUI. The GUI was not executed in spite of activating the settings of the Vagrant file. Although we manually installed GDM, gnome-shell, and ubuntu-gnome-desktop (to boot in to a graphical interface, add a file manager, add/fix a terminal, ... ), would you prefer to add appropriate settings to the Vagrant image? 

There is a similar discussion on the following link.
https://stackoverflow.com/questions/18878117/using-vagrant-to-run-virtual-machines-with-desktop-environment

**Comment by g-oikonomou** [comment]
#1276
