### ISSUE TITLE
nRF52832 hello-world.flash unknown rule - How to flash it?

### ISSUE THREAD

**Issue by TT-SWP13** [contiki-ng/contiki-ng#782]
Hello,

i like to flash the hello-world example on my nRF52823 over USB.
Is there an other way to flash it with Contiki-**NG**?
I follow the tutorial steps from Contiki-**OS**.:

- https://github.com/contiki-os/contiki/tree/master/platform/nrf52dk

But the command "_make TARGET=nrf52dk BOARD=nrf52832 PORT=/dev/ttyACM0 hello-world.flash_"
produce this error in Contiki-NG:

```
SDK: /home/pi/nrf5x-sdk2
SoftDevice: /home/pi/nrf5x-sdk2/components/softdevice/s1xx_iot/s1xx-iot-prototype3_nrf52_softdevice.hex
make: *** Keine Regel, um „hello-world.flash“ zu erstellen.  Schluss.
```

**My commands**
1. sudo su 
2. export NRF52_SDK_ROOT=/home/pi/nrf5x-sdk2
3. export NRF52_JLINK_PATH=/home/pi/JLink_Linux_V640_arm/
4. make TARGET=nrf52dk BOARD=nrf52832 PORT=/dev/ttyACM0 clean
5. make TARGET=nrf52dk BOARD=nrf52832 PORT=/dev/ttyACM0 erase
6. make TARGET=nrf52dk BOARD=nrf52832 PORT=/dev/ttyACM0 softdevice.flash
7. make TARGET=nrf52dk BOARD=nrf52832 PORT=/dev/ttyACM0 hello-world.flash --> ERROR
(8. make TARGET=nrf52dk BOARD=nrf52832 PORT=/dev/ttyACM0 hello-world)

**With Contiki-OS it works fine. How can i flash it with Contiki-NG? Thanks!**

**Comment by g-oikonomou** [comment]
Thank you for reporting this. I can confirm this as a bug. #784 fixes it.

**Comment by TT-SWP13** [comment]
Thank you very much! Now it works.
