### ISSUE TITLE
cooja platform does not have mutex, memory-barrier or int-master

### ISSUE THREAD

**Issue by debug-ito** [contiki-ng/contiki-ng#790]
I'm working on #764. My current plan is to use sys/mutex to protect the event queue.

Bad news is that cooja platform does not have implementation of sys/mutex, sys/memory-barrier or sys/int-master. I'm not sure how I should implement them for cooja. Any advice?

**Comment by g-oikonomou** [comment]
TBH I'd just provide empty stubs...

**Comment by debug-ito** [comment]
Fixed by #791
