### ISSUE TITLE
RF_runCmd hangs after changing channel in the callback function of rtimer on Simplelink CC1352

### ISSUE THREAD

**Issue by mleefiti** [contiki-ng/contiki-ng#816]
Dear all:

   I would like to change channel in the callback function of rtimer.
However, CC1352 was hanged when I called NETSTACK_RADIO.set_value(RADIO_PARAM_CHANNEL,channel) to switch channel. 
After tracing codes, I found that CC1352 was hanged on RF_runCmd() in netstack_sched_fs() of arch/cpu/simplelink-cc13xx-cc26xx/rf/sched.c. 
If I changed channel outside of the callback function of rtimer, it worked fine.
Any suggestion is welcome.

**Comment by mleefiti** [comment]
Mr. Ross, Thanks for your explanation.

**Comment by bbhagasra1** [comment]
What is the solution of this issue?
