### ISSUE TITLE
wiki-Creating alias during Docker setup

### ISSUE THREAD

**Issue by reubenct** [contiki-ng/contiki-ng#823]
While I was following the [setup instructions for docker image](https://github.com/contiki-ng/contiki-ng/wiki/Docker#Setup) of contiki-ng, the last part of the section tells how to create a new bash alias which creates the container when user runs contiker.
```bash
$ contiker
``` 
The wiki instructs us to add the alias definition in `~/.profile`. But this didn't work for me. Rather the entry should be added to `~/.bashrc` instead. ([credits](https://askubuntu.com/a/272500/796752))
```
export CNG_PATH=<absolute-path-to-your-contiki-ng>
alias contiker="docker run --privileged --mount type=bind,source=$CNG_PATH,destination=/home/user/contiki-ng -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v /dev/bus/usb:/dev/bus/usb -ti contiker/contiki-ng"
```

**Comment by yatch** [comment]
According to the `bash` manual, `.profile` is read when you login if neither `~/.bash_pro-file` nor `~/.bash_login` is available. The alias in your `.profile` may get enabled after logout and login. Adding the alias to `.bashrc~ is another option, for sure.

I've updated the wiki page. Thanks!
