### ISSUE TITLE
Fix the confusing name srf06-cc26xx

### ISSUE THREAD

**Issue by simonduq** [contiki-ng/contiki-ng#83]
At least I am confused, as this also contains cc13xx. 
Any way to make things clearer? And easier to type?

**Comment by g-oikonomou** [comment]
@yatch after current open pulls get merged we'll be good to work on this. I'm flagging it for next release.

**Comment by yatch** [comment]
@g-oikonomou 👍

**Comment by yatch** [comment]
@simonduq I got it 👍

**Comment by simonduq** [comment]
Postponing to 4.2, as we will need more time to make sure doc, examples and everything remains consistent after the change.

**Comment by firmwareguru** [comment]
You know what, I wouldn't make any official changes here until a working port to the cc13x2 or cc26x2 device is made.  I'm taking a cursory look at that now, having a couple of LAUNCHXL-CC1312R1's on my desk.

From a platform perspective, they are very similar.  I would almost say cc13xx-cc26xx is still appropriate as a name.  From a cpu perspective, again, very similar and the ti-lib abstraction layer may be able to handle most of it.  The cc13x2 device SDK comes with an updated "cc13xxware" called "cc13x2_cc26x2_v1".   This new directory would sit under cpu/cc26xx-cc13xx/lib.   Looks as if 'rf-core' has been restructured - would need to take a look at that.

All in all these second generation parts maintain a high degree of compatibility with their predecessors, so there are significant code sharing opportunities.

**Comment by simonduq** [comment]
SO, the PR is ready (https://github.com/contiki-ng/contiki-ng/pull/387), but because this change will outdate documentation and may affect external tools, we decided to merge straight *after* the feature-freeze, i.e., have this in develop very soon, but only released 6 months later (4.3).
