### ISSUE TITLE
Platform zoul: power-mgmt module's pm_get_voltage() does not return correct measurements

### ISSUE THREAD

**Issue by lukasostendorf** [contiki-ng/contiki-ng#832]
The function pm_get_voltage() in arch/platform/zoul/remote-revb/power-mgmt.c does not return correct voltage readings.

Here are the results of measuring the voltage every 10seconds:
![pm_get_voltage_raw](https://user-images.githubusercontent.com/44869119/51688222-706a3280-1ff4-11e9-9bd6-7912ac08f59a.png)

In a branch of Zolertia's contiki repository I've [found a fix](https://github.com/Zolertia/contiki/commit/aafc740211417c9c46c1a5f1cda7a63e86bb2bf0) for this. Apparently they use the following conversion:
`voltage = -181.9*(register_val - 1294.72)`

The converted measurements are here:

![pm-get-voltage-fixed](https://user-images.githubusercontent.com/44869119/51688550-203fa000-1ff5-11e9-91dc-ba53571d1abc.png)

I'm not sure whether this fitting is suitable for different battery types, but still the conversion seems more useful than the current result of the function. Therefore, I'd include the conversion also in contiki-ng.

I do not know whether I'm allowed to "copy" the commit (and refer to it in my PR?). That's why I did not come up with a PR immediately.

**Comment by g-oikonomou** [comment]
Thanks for this. I'll flag it as a bug to make sure it doesn't fall through the cracks.

**Comment by g-oikonomou** [comment]
Hi @lukasostendorf can you have a look at #902 if you get a chance?
