### ISSUE TITLE
Documentation: Fix typos in the Docker wiki page

### ISSUE THREAD

**Issue by Muskuloese** [contiki-ng/contiki-ng#836]
While going through the documentation, I noticed a few typos in the Docker documentation page, e.g., DockerHub was spelled DuckerHub. 

I updated the page using the `wiki-sanbox` as suggest: https://github.com/contiki-ng/wiki-sandbox/wiki/Docker

**Comment by yatch** [comment]
Thanks! I've updated the wiki page:

 https://github.com/contiki-ng/contiki-ng/wiki/Docker/_compare/a73ff5fe985afb4d79bd992e929d9e9f83e71e0b...5f4f56d5c71d1f47e582b5b552ab38e1ad7e9a25
