### ISSUE TITLE
RPL Leaf only

### ISSUE THREAD

**Issue by admachin** [contiki-ng/contiki-ng#838]
I've been trying to use RPL as leaf only mode with RPL Lite. In documentation is specified that RPL_CONF_LEAF_ONLY macro should be set if leaf only mode is wanted, but for RPL Lite the macro that control leaf only mode is RPL_CONF_DEFAULT_LEAF_ONLY instead.

**Comment by simonduq** [comment]
Fixed, thanks for reporting
