### ISSUE TITLE
Correct interpretation of PowerTracker output.

### ISSUE THREAD

**Issue by abhiverma866** [contiki-ng/contiki-ng#840]
![screenshot from 2019-02-06 12-13-40](https://user-images.githubusercontent.com/16736201/52324921-25dfb180-2a09-11e9-8e39-00ad7b453b81.png)
![screenshot from 2019-02-06 12-13-45](https://user-images.githubusercontent.com/16736201/52324922-26784800-2a09-11e9-8520-5525ec2ba9aa.png)

**Comment by domenickmorales** [comment]
Can you elaborate about the correct interpretation of PowerTracker output, please?
