### ISSUE TITLE
Enable TSCH Debug on cc26x0-cc13x0 plataform

### ISSUE THREAD

**Issue by Yagoor** [contiki-ng/contiki-ng#869]
I'm currently working on a project using the CC1350 board and I realised that it doesn't support the TSCH DEBUG Macros, in fact only the jn516x platform supports.

I'm going to implement these macros in the cc26x0-cc13x0 plataform and I'll expose a macro that can be enabled in the project-conf so that the developer can either enable or disable this functionality.

Is there something I need to be aware while doing this implementation? I'll gladly make a pull request after I have done this implementation.

The macros that I'm referring are as follows:

#define TSCH_DEBUG_INIT()
#define TSCH_DEBUG_INTERRUPT()
#define TSCH_DEBUG_RX_EVENT()
#define TSCH_DEBUG_TX_EVENT()
#define TSCH_DEBUG_SLOT_START()
#define TSCH_DEBUG_SLOT_END()

Best Regards,

**Comment by g-oikonomou** [comment]
I think some (all?) of those happen inside an interrupt context, so I would advise against printing things. It looks like the best approach here is to toggle a GPIO line, that you can then use with a logic analyser for debugging.

I would personally like to see a way to easily enable/disable those things. I would recommend default: disabled.
