### ISSUE TITLE
cc26xx-web-demo running LP cc1310 Sensor node is not joining 6lbr web page

### ISSUE THREAD

**Issue by cliftonbm** [contiki-ng/contiki-ng#875]
We have 1 cc1310 launchpad running slip-radio and another cc1310 LP running cc26xx-web-demo and 6lbr running on linux machine.
when we open web bbbb::100] sensor node is not detecting
what could be the problem?

**Comment by chenek** [comment]
Try to refer to https://github.com/contiki-ng/contiki-ng/issues/431
