### ISSUE TITLE
cc26x0-cc13x0 radio drivers: `read_frame` logic is not consistent with `pending_packet`

### ISSUE THREAD

**Issue by atiselsts** [contiki-ng/contiki-ng#879]
The `read_frame` function looks only at the first buffer. The `pending_packet` function loops through all buffers. As a result, this may happen:

```
int length = 0;
if(NETSTACK_RADIO.pending_packet(...)) {
   length = NETSTACK_RADIO.read(...); /* returns 0 */
}
```
After this:
- `length` is zero
- the packet is still in the radio's buffers
- subsequent calls to `NETSTACK_RADIO.pending_packet(...)` return true
- subsequent calls to `NETSTACK_RADIO.read(...)` return zero

Looking at the code, this situation fixes itself only after more packets are received, or the radio is reinitialized.

**Comment by g-oikonomou** [comment]
Fixed in #1083
