### ISSUE TITLE
Compilation error when RPL probing is disabled.

### ISSUE THREAD

**Issue by hseokman** [contiki-ng/contiki-ng#891]
I created a project-conf.h file with
#define RPL_CONF_WITH_PROBING 0
on rpl-udp example code.

remove_neighbor function in
os/net/routing/rpl-lite/rpl-neighbor.c 
and
rpl_link_callback function in
os/net/routing/rpl-lite/rpl.c

gives compilation error because both reference urgent_probing_target  which is excluded in the header file when probing is disabled.

**Comment by g-oikonomou** [comment]
Thanks for the report. I can confirm this as a bug. Fix in #904
