### ISSUE TITLE
RPL DAO message has incorrect checksum

### ISSUE THREAD

**Issue by hseokman** [contiki-ng/contiki-ng#892]
I used Cooja simulator to simulate RPL-UDP example.
I exported radio message to PCAP and opened with wireshark.
Cooja simulator does not correctly decode or show the content of the DAO message.
Wireshark decodes the DAO message, but shows incorrect checksum.
This is one of the message

Frame 2: 85 bytes on wire (680 bits), 85 bytes captured (680 bits)
IEEE 802.15.4 Data, Dst: EquipTra_01:00:01:00:01, Src: NetSys_02:00:02:00:02
6LoWPAN, Src: ::202:2:2:2, Dest: ::201:1:1:1
Internet Protocol Version 6, Src: ::202:2:2:2, Dst: ::201:1:1:1
Internet Control Message Protocol v6
    Type: RPL Control (155)
    Code: 2 (Destination Advertisement Object)
    Checksum: 0x5b40 incorrect, should be 0x5542
        [Expert Info (Warning/Checksum): Bad checksum [should be 0x5542]]
            [Bad checksum [should be 0x5542]]
            [Severity level: Warning]
            [Group: Checksum]
    [Checksum Status: Bad]
    RPLInstanceID: 0
    Flags: 0x80, DAO-ACK Request (K)
    Reserved: 00
    DAO Sequence: 241
    ICMPv6 RPL Option (RPL Target fd00::202:2:2:2/128)
    ICMPv6 RPL Option (Transit Information fd00::201:1:1:1)

0000   61 dc f7 cd ab 01 00 01 00 01 00 01 00 02 00 02   a...............
0010   00 02 00 02 00 7e f7 00 e0 3a 06 63 04 00 00 02   .....~...:.c....
0020   00 9b 02 5b 40 00 80 00 f1 05 12 00 80 fd 00 00   ...[@...........
0030   00 00 00 00 00 02 02 00 02 00 02 00 02 06 14 00   ................
0040   00 00 1e fd 00 00 00 00 00 00 00 02 01 00 01 00   ................
0050   01 00 01 bc c4                                    .....

I attached full log of the simulation.

[radiolog-1554239942597.zip](https://github.com/contiki-ng/contiki-ng/files/3035970/radiolog-1554239942597.zip)

**Comment by yatch** [comment]
You need to set Context 0 to `fd00::/64` in 6LoWPAN settings in the Preferences dialog. See the screenshot attached here:
![wireshark](https://user-images.githubusercontent.com/1230923/55437565-7d307700-559f-11e9-931d-8f8f034c380a.png)
