### ISSUE TITLE
XQuartz slow on MacOS

### ISSUE THREAD

**Issue by PkLearning** [contiki-ng/contiki-ng#895]
<a href="https://ibb.co/dJgqc3Z"><img src="https://i.ibb.co/3Yzqs8K/Screen-Shot-2562-04-07-at-19-28-03.png" alt="Screen-Shot-2562-04-07-at-19-28-03" border="0"></a>

GUI is not good

How to optimize ?

**Comment by g-oikonomou** [comment]
Yes, I have some problems too, although in my situation it's not quite as bad...

@simonduq @nfi have you tried this on macOS? What do things look like your end?
