### ISSUE TITLE
Understanding the MAC, RDC and framer layers configuration

### ISSUE THREAD

**Issue by StefanHri** [contiki-ng/contiki-ng#899]
I am trying to understand the MAC layer configuration of contiki-ng. I found the tutorial here:

https://anrg.usc.edu/contiki/index.php?title=MAC_protocols_in_ContikiOS&printable=yes

but since this tutorial is for ContikiOS 2.7 it seams to be outdated and non-relevant for contiki-ng v4.2 which I want to use.
Where to find documentation of the implemented by contiki-ng MAC, RDC and framer layers? What is the default configuration of those layers and how I may change it?

**Comment by g-oikonomou** [comment]
Hi @StefanHri the best place to look at is: https://github.com/contiki-ng/contiki-ng/wiki/The-Contiki%E2%80%90NG-configuration-system

I'm closing this. Feel free to join us on gitter!
