### ISSUE TITLE
6TiSCH and nRF52840

### ISSUE THREAD

**Issue by dragondgold** [contiki-ng/contiki-ng#911]
Hello, I'm looking to implement 6TiSCH on the nRF52840 CPU. According to [this tweet](https://twitter.com/contiki_ng/status/1065232696128008192) nRF52840 support is on its way, is there any update on this?

Also, according to the 6TiSCH docs the nRF52840 is not supported, would it be difficult to port it to this new chipset? I will be more than happy to make the port and share it.

**Comment by g-oikonomou** [comment]
Hi

There is an effort to add support for the nRF52840. I don't have an ETA, but it's definitely in the wishlist. I'm closing this, do join us on gitter if you fancy discussing this more.
