### ISSUE TITLE
TSCH does not work on CC1312r1

### ISSUE THREAD

**Issue by hseokman** [contiki-ng/contiki-ng#928]
It seems CC1312 prop-mode radio driver is not fully implemented to support TSCH yet.
The example code is compiled but gives an error in TSCH initialization with this message.

radio does not support getting RADIO_PARAM_RX_MODE

I don't see case statement for RADIO_PARAM_RX_MODE in
get_value function in arch/cpu/simplelink-cc13xx-cc26xx/rf/prop-mode.c

**Comment by zhuqiyun** [comment]
focus

**Comment by g-oikonomou** [comment]
#1038
