### ISSUE TITLE
while cycle in contiki process

### ISSUE THREAD

**Issue by NeoN7777** [contiki-ng/contiki-ng#930]
Hello guys. I have some problem in my code.

    while(eventFlag) {
        if(TimerValueGet(GPT1_BASE, TIMER_B) < 20000) eventFlag = false;
    }

I'm waiting for triggering an interrupt event which changes 'eventFlag to zero'. But when flag have changed, the while cycle doesn't stop, until TIMER_B expired. I put printf function into the while cycle and it worked. I think it workes because printf uses interrupt too. Can you explain me why this happens? And how make this code work without printf.

**Comment by yatch** [comment]
You may want to look at `process` APIs for such a synchronization.

https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-Processes-and-events
https://github.com/contiki-ng/contiki-ng/blob/develop/os/sys/process.h
