### ISSUE TITLE
TSCH is sending EB when the RPL prefered parent is NULL

### ISSUE THREAD

**Issue by atiselsts** [contiki-ng/contiki-ng#933]
In RPL classic, the `joined` flag of a dag might be set even if the node does not have a preferred parent. As a result, TSCH may continue to send EB and create infinite timesource loops. I did not investigate whether this problem also applies to RPL lite.

According to [RFC 8180](https://tools.ietf.org/html/rfc8180#section-6.3):

>  When a RPL node joins the network, it MUST NOT send EBs before having
>   acquired a RPL Rank to avoid inconsistencies in the time
>   synchronization structure.  This applies to other routing protocols
>   with their corresponding routing metrics.  As soon as a node acquires
>   routing information (e.g., a RPL Rank, see Section 5.1.1), it SHOULD
>   start sending EBs.

Since the spirit / desired outcome of this paragraph is "to avoid inconsistencies in the time synchronization structure" I think that the RPL "has joined" functionality should be improved to also take into account parent state.

**Comment by debug-ito** [comment]
In rpl-lite, the dag object goes to the JOINED state after it finds the preferred parent (https://github.com/contiki-ng/contiki-ng/blob/fb6451ef7b3f32e12d3ec0d7fe1de34476e4b4a0/os/net/routing/rpl-lite/rpl-dag.c#L330 ).

**Comment by g-oikonomou** [comment]
Fixed in #1106
