### ISSUE TITLE
Cannot run out-of-tree tests inside docker

### ISSUE THREAD

**Issue by g-oikonomou** [contiki-ng/contiki-ng#961]
As reported in #897, it is currently impossible to test out-of-tree builds inside off-the-shelf docker.

Those builds rely on on [contiki-ng/out-of-tree-tests](https://github.com/contiki-ng/out-of-tree-tests) being mounted at `$(HOME)/out-of-tree-tests`, but in our current docker image it is not: It only gets mounted inside travis by `.travis.yml`.

Edit: I wonder whether this is simply a case of changing the `contiker` alias.

**Comment by simonduq** [comment]
Yes it does sound like a `contikier` issue: you need a virtual mount, something like: `-v $CNG_PATH:/home/user/contiki-ng/out-of-tree-tests` (maybe you also need `--mount type=bind,source=... destination=...`

**Comment by g-oikonomou** [comment]
https://github.com/contiki-ng/contiki-ng/wiki/Docker#running-out-of-tree-tests
