### ISSUE TITLE
MPL Documentation Missing

### ISSUE THREAD

**Issue by edrose** [contiki-ng/contiki-ng#979]
MPL Documentation is missing from the IPv6 multicast page in the Wiki, it's still listed as a future improvement. There are a few things that people who are using it may need to be aware of, so it could do with a little documentation. I'm happy to put something together quickly in my spare time if needed.

**Comment by g-oikonomou** [comment]
I've edited the wiki page to document MPL support. Feel free to send more our way if you happen to find time Ed. Closing for now.
