### ISSUE TITLE
TSCH powercycling

### ISSUE THREAD

**Issue by g-oikonomou** [contiki-ng/contiki-ng#980]
At the start of timeslots we do this:

```
      if(is_active_slot) {
        [...]
        /* Turn the radio on already here if configured so; necessary for radios with slow startup */
        tsch_radio_on(TSCH_RADIO_CMD_ON_START_OF_TIMESLOT);
```

Now if `TSCH_RADIO_ON_DURING_TIMESLOT` is 0 then the above call will not turn on the radio. Unless `TSCH_CCA_ENABLED` is 1 then we will call `NETSTACK_RADIO.transmit(packet_len);` inside the TX slot operation without explicitly turning the radio on.

Am I looking at a bug?

**Comment by atiselsts** [comment]
No, because the radio driver will turn on the radio for the transmission and then turn it back off. Or is this question related to the "radio driver semantics" issue?
