### ISSUE TITLE
Last node in the dag

### ISSUE THREAD

**Issue by PranavD10** [contiki-ng/contiki-ng#981]
Hey,
How can I find the last node in the DAG if I use RPL-lite?
Thank you

**Comment by debug-ito** [comment]
What do you mean by "the last node"? A leaf node, i.e., a node with no children ??

**Comment by PranavD10** [comment]
I want to find the DAG structure the nodes are connected...how will I know that...???

**Comment by debug-ito** [comment]
If you use rpl-lite, `rpl_neighbor_print_list` function (os/net/routing/rpl-lite/rpl-neighbor.h) prints the list of RPL neighbors, which includes the preferred parent node. By combining that information from all nodes in the DAG, you can construct the upward routes (DAG). In addition, calling `rpl_dag_root_print_links` (os/net/routing/rpl-lite/rpl-dag-root.h) in the root node will show all entries in the source routing table. That corresponds to the downward routes.
