### ISSUE TITLE
6Lowpan Fragmentation Header

### ISSUE THREAD

**Issue by ad7406761** [contiki-ng/contiki-ng#984]
Hi all,

 I'm new to contiki ng. I try mqtt-client example with cc1310. in that i can able to publish a data to mqtt broker. when i tired to send a data from Broker to Client, Client not received the packet. i saw the 6LoWPAN packet with Fragmentation Header in sensniff with publish data from Server to Client. 

Setup:
Border router running in Raspberry Pi.
Slipradio in CC1310 {Connected to Raspberry Pi}.
Mqtt-Client running in CC1310.

**Comment by g-oikonomou** [comment]
As far as I can see, building the mqtt-client for `TARGET=cc26x0-cc13x0 BOARD=launchpad/cc1310` uses the following settings by default:

```
$ make TARGET=cc26x0-cc13x0 BOARD=launchpad/cc1310 viewconf
----------------- Make variables: --------------
##### "TARGET": ________________________________ cc26x0-cc13x0
##### "BOARD": _________________________________ launchpad/cc1310
##### "MAKE_MAC": ______________________________ MAKE_MAC_CSMA
##### "MAKE_NET": ______________________________ MAKE_NET_IPV6
##### "MAKE_ROUTING": __________________________ MAKE_ROUTING_RPL_LITE
----------------- C variables: -----------------
[...]
##### "UIP_CONF_BUFFER_SIZE": __________________ == 1280
[...]
##### "SICSLOWPAN_CONF_FRAG": __________________ == 1
##### "SICSLOWPAN_CONF_COMPRESSION": ___________ == SICSLOWPAN_COMPRESSION_IPHC
[...]
```
These look OK and they match the configuration of the slip-radio. How large a packet did you try to send from the broker to the client? What was in it? Are you sure the client did not receive it at all (as opposed to receiving it and ignoring it)?
